### ISSUE TITLE
Matrix: DVDAudioCodec.h:109:62: error: ‘AV_MATRIX_ENCODING_NONE’ was not declared in this scope

### ISSUE THREAD

**Issue by candrews** [xbmc/xbmc#20894]
### Describe the bug
Here is a clear and concise description of what the problem is:

Compiling the Kodi "Matrix" branch 62b06097c1bb3ed87e9a680ba92266682e88818f results against ffmpeg 5.0 results in this build time error:
```
/var/tmp/portage/media-tv/kodi-19.9999/work/kodi-19.9999/xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodec.h:109:62: error: ‘AV_MATRIX_ENCODING_NONE’ was not declared in this scope
  109 |   virtual enum AVMatrixEncoding GetMatrixEncoding() { return AV_MATRIX_ENCODING_NONE; }
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~~
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Successful build resulting in a functional Kodi

## Actual Behavior

```
FAILED: build/cores/paplayer/CMakeFiles/paplayer.dir/VideoPlayerCodec.cpp.o 
/usr/lib/ccache/bin/x86_64-pc-linux-gnu-g++  -I/var/tmp/portage/media-tv/kodi-19.9999/work/kodi-19.9999_build -I/var/tmp/portage/media-tv/kodi-19.9999/work/kodi-19.9999 -I/var/tmp/portage/media-tv/kodi-19.9999/work/kodi-19.9999/lib -I/var/tmp/portage/media-tv/kodi-19.9999/work/kodi-19.9999/xbmc -I/var/tmp/portage/media-tv/kodi-19.9999/work/kodi-19.9999/xbmc/platform/linux -I/var/tmp/portage/media-tv/kodi-19.9999/work/kodi-19.9999/xbmc/cores/VideoPlayer -I/var/tmp/portage/media-tv/kodi-19.9999/work/kodi-19.9999_build/build -I/var/tmp/portage/media-tv/kodi-19.9999/work/kodi-19.9999_build/build/include -I/var/tmp/portage/media-tv/kodi-19.9999/work/kodi-19.9999/xbmc/platform/posix -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/python3.9 -I/usr/include/libxml2 -I/var/tmp/portage/media-tv/kodi-19.9999/work/kodi-19.9999_build/build/cores/RetroPlayer/messages -I/usr/include/freetype2 -I/usr/include/fribidi -I/var/tmp/portage/media-tv/kodi-19.9999/work/kodi-19.9999/xbmc/contrib -I/var/tmp/portage/media-tv/kodi-19.9999/work/kodi-19.9999_build/build/libdvd/include -I/usr/include/lzo -I/usr/include/libdrm  -O2 -march=native -pipe -fuse-linker-plugin -flto -Wl,-flto -ftree-vectorize -falign-functions=32 -fgraphite-identity -floop-nest-optimize -fno-common -fno-lto -fno-use-linker-plugin -ggdb -DNDEBUG -Wall -DTARGET_POSIX -DTARGET_LINUX -D_GNU_SOURCE -DHAVE_LINUX_UDMABUF=1 -DHAVE_LINUX_DMA_HEAP=1 -DHAVE_LINUX_DMA_BUF=1 -DHAVE_MKOSTEMP=1 -DHAVE_LINUX_MEMFD=1 -DHAVE_STATX=1 -DHAVE_SSE=1 -DHAVE_SSE2=1 -DHAVE_SSE3=1 -DHAVE_SSSE3=1 -DHAVE_SSE4_1=1 -DHAVE_SSE4_2=1 -DHAVE_AVX=1 -DHAVE_AVX2=1 -D__STDC_CONSTANT_MACROS -D_FILE_OFFSET_BITS=64 -DHAS_POSIX_NETWORK -DHAS_LINUX_NETWORK -DHAS_BUILTIN_SYNC_ADD_AND_FETCH=1 -DHAS_BUILTIN_SYNC_SUB_AND_FETCH=1 -DHAS_BUILTIN_SYNC_VAL_COMPARE_AND_SWAP=1 -DHAVE_INOTIFY=1 -DHAVE_POSIX_FADVISE=1 -DHAVE_LOCALTIME_R=1 -DHAVE_GMTIME_R=1 -DHAVE_INTTYPES_H=1 -DHAS_ALSA=1 -DHAS_AVAHI=1 -DHAS_ZEROCONF=1 -DHAVE_LIBBLURAY=1 -DHAVE_LIBBLURAY_BDJ=1 -DHAVE_LIBCEC=1 -DHAS_DBUS=1 -DHAS_ISO9660PP=1 -DHAVE_LCMS2=1 -DHAS_WEB_SERVER=1 -DHAS_WEB_INTERFACE=1 -DHAS_PULSEAUDIO=1 -DHAS_PYTHON=1 -DHAVE_LIBUDEV=1 -DHAS_UDFREAD=1 -DHAVE_LIBXSLT=1 -DHAVE_LIBVA=1 -DFFMPEG_VER_SHA=\"undef\" -I/usr/include/fribidi -DSPDLOG_FMT_EXTERNAL -DSPDLOG_DEBUG_ON -DSPDLOG_NO_ATOMIC_LEVELS -DSPDLOG_ENABLE_PATTERN_PADDING -DHAVE_WAYLAND=1 -DHAVE_HDR_OUTPUT_METADATA=1 -DHAS_GLES=3 -DHAS_EGL=1 -DHAVE_X11=1 -DHAVE_LIBXRANDR=1 -DHAS_UPNP=1 -DHAS_DVD_DRIVE -DHAS_CDDA_RIPPER -DBIN_INSTALL_PATH=\"/usr/lib64/kodi\" -DINSTALL_PATH=\"/usr/share/kodi\" -std=c++14 -MD -MT build/cores/paplayer/CMakeFiles/paplayer.dir/VideoPlayerCodec.cpp.o -MF build/cores/paplayer/CMakeFiles/paplayer.dir/VideoPlayerCodec.cpp.o.d -o build/cores/paplayer/CMakeFiles/paplayer.dir/VideoPlayerCodec.cpp.o -c /var/tmp/portage/media-tv/kodi-19.9999/work/kodi-19.9999/xbmc/cores/paplayer/VideoPlayerCodec.cpp
In file included from /var/tmp/portage/media-tv/kodi-19.9999/work/kodi-19.9999/xbmc/cores/paplayer/VideoPlayerCodec.h:12,
                 from /var/tmp/portage/media-tv/kodi-19.9999/work/kodi-19.9999/xbmc/cores/paplayer/VideoPlayerCodec.cpp:9:
/var/tmp/portage/media-tv/kodi-19.9999/work/kodi-19.9999/xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodec.h:42:8: error: use of enum ‘AVMatrixEncoding’ without previous declaration
   42 |   enum AVMatrixEncoding matrix_encoding;
      |        ^~~~~~~~~~~~~~~~
/var/tmp/portage/media-tv/kodi-19.9999/work/kodi-19.9999/xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodec.h:109:16: error: use of enum ‘AVMatrixEncoding’ without previous declaration
  109 |   virtual enum AVMatrixEncoding GetMatrixEncoding() { return AV_MATRIX_ENCODING_NONE; }
      |                ^~~~~~~~~~~~~~~~
/var/tmp/portage/media-tv/kodi-19.9999/work/kodi-19.9999/xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodec.h: In member function ‘virtual int CDVDAudioCodec::GetMatrixEncoding()’:
/var/tmp/portage/media-tv/kodi-19.9999/work/kodi-19.9999/xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodec.h:109:62: error: ‘AV_MATRIX_ENCODING_NONE’ was not declared in this scope
  109 |   virtual enum AVMatrixEncoding GetMatrixEncoding() { return AV_MATRIX_ENCODING_NONE; }
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

### To Reproduce

1. Install ffmpeg 5.0
2. Build kodi "Matrix" with `-DENABLE_INTERNAL_FFMPEG=no`

### Debuglog

The debuglog can be found here:

[build.log](https://github.com/xbmc/xbmc/files/7926022/build.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

n/a

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Gentoo/Linux
 - Kodi version: Matrix

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by a1rwulf** [comment]
Matrix doesn't work with ffmpeg 5.0

**Comment by candrews** [comment]
> Matrix doesn't work with ffmpeg 5.0

I noticed, that's what I'm reporting :)

Does master work with ffmpeg 5? If so, could that patch be backported to Matrix?

**Comment by a1rwulf** [comment]
No even master is using ffmpeg 4.4 at the moment.
We've started some work to check our code in relation to ffmpeg 5.0, but nothing concrete as of now.
I don't think we'll backport those changes.

**Comment by wsnipex** [comment]
to be clear: Matrix uses ffmpeg 4.3, everything else is unsupported
