### PR TITLE
AddonDatabase: fix build with gcc-4.9

### PR DESCRIPTION
**Pull request by bkuhls**
Suggested by yasji:
https://forum.kodi.tv/showthread.php?tid=358086&pid=2994354#pid2994354

## Description
Fixes a build error with gcc-4.9, first found with gcc-4.9.1
```
output/host/opt/ext-toolchain/aarch64-amd-linux-gnu/include/c++/4.9.1/ext/new_allocator.h: In instantiation of 'void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = std::pair<std::basic_string<char>, ADDON::SExtValue>; _Args = {std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >}; _Tp = std::pair<std::basic_string<char>, ADDON::SExtValue>]':

output/build/kodi-efa9ec691491ea3311f8de36b16b665f188afef4/xbmc/addons/AddonDatabase.cpp:172:90:   required from here
output/host/opt/ext-toolchain/aarch64-amd-linux-gnu/include/c++/4.9.1/ext/new_allocator.h:120:4: error: no matching function for call to 'std::pair<std::basic_string<char>, ADDON::SExtValue>::pair(std::basic_string<char>, std::basic_string<char>)'
```
## How Has This Been Tested?
Build- and runtime-tested with gcc-4.9.2
```
Starting Kodi (19.0-BETA2 (18.9.821) Git:20201211-96e386e88b78c009). Platform: Linux x86 64-bit
Using Debug Kodi x64
Kodi compiled 2020-12-11 by GCC 4.9.2 for Linux x86 64-bit version 3.16.7 (200711)
```
## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document

### CODE REVIEW

**Comment by lrusak** [comment]
Probably fine. I would highly recommend updating your compiler and kernel version though.

**Comment by wsnipex** [comment]
this is not a fix. Kodi requires C++14

**Comment by bkuhls** [comment]
> this is not a fix. Kodi requires C++14

I am not an expert when it comes to c++ standards but according to https://gcc.gnu.org/projects/cxx-status.html#cxx14 the gcc-4.9 suite should support c++14. The kodi docs say the same:
https://github.com/xbmc/xbmc/commit/bd6818f1975ef4665d2319b482460f64aa4ae277#diff-27813645725d98702bb30724d335089b706f714028c01038a0f6f5d0ce5dfd86

The code in question uses std::pair https://github.com/xbmc/xbmc/blob/b694296acd75fc470b08c56826b2f8bc59d387b3/xbmc/addons/AddonDatabase.cpp#L168
which is based on the
```
"Improving pair and tuple" feature that was added to the draft C++ standard after C++14 was released
```
https://stackoverflow.com/a/47284746

so this PR should be committed to kodi to support gcc-4.9.

I hope this sounds convincing, again: I am not an expert ;)

**Comment by wsnipex** [comment]
yes and no. You are right that the code is not valid c++14, so your change is valid.
But that doesn't mean that gcc 4.9 is C++14 compliant, as the page you linked clearly states.

**Comment by yasij** [comment]
I suggested the change to get your build to work, but I didn't actually author this. Can you change the author to yourself? (Otherwise, you'll need approval from my employer to submit that).

**Comment by bkuhls** [comment]
> Can you change the author to yourself?

Done

**Comment by bkuhls** [comment]
jenkins fails with
```
ERROR: $GIT_COMMIT (0e3ddeface7be276ab0f110e49d7826d68cafe14) doesn't match currently checked out revision (fa6c995996049daa72e4412703c6a4391382d44e)
Build step 'Execute shell' marked build as failure
```
Is there anything I can do to fix this problem?

**Comment by fuzzard** [comment]
Rule of thumb is don't force push if it's pending a build. Breaks all subsequent builds for the PR.

Jenkins build this please
