### PR TITLE
[Video] Fix GetMovieName(), GetMovieBasePath() and GetBasePath() to better handle optical media, bluray:// paths and Disc n subdirectories. Add tests.

### PR DESCRIPTION
**Pull request by 78andyp**
## Description

Probably easiest to look at the tests and see if they are what you would expect.

Looking at the existing code - basepath is different to the actual path of the media file, it is where the actual physical file resides.

There are also issues with the handling of bluray:// paths and Disc n paths in terms of movie name derivation from the path.

## Motivation and context

When adding bluray movie nfo support several scenarios came to light during testing where the movie name was not being properly derived from the path.

This fixes that.

## How has this been tested?

Tests.
Locally.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

File: xbmc/utils/URIUtils.cpp [hunk 1]
```diff
@@ -450,23 +451,32 @@ bool URIUtils::GetParentPath(const std::string& strPath, std::string& strParent)
...
-    GetParentPath(strPath, strDirectory);
+    std::string path{strDirectory};
+    GetParentPath(path, strDirectory);
   }
+
+  if (IsBDFile(strCheck))
+    strDirectory = GetDiscBasePath(strCheck);
+
+  if (IsBlurayPath(strCheck))
+    strDirectory = CBlurayDirectory::GetBasePath(CURL(strCheck));
```
Comment (howie-f) [inline xbmc/utils/URIUtils.cpp:471]: did this pass ci? i'm getting a linker error when building on Debian 12
```
[100%] Linking CXX executable kodi-x11
build/utils/utils.a(URIUtils.cpp.o):URIUtils.cpp:function URIUtils::GetBasePath(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&):

error: undefined reference to 'XFILE::CBlurayDirectory::GetBasePath[abi:cxx11](CURL const&)'
collect2: error: ld returned 1 exit status

gmake[2]: *** [CMakeFiles/kodi.dir/build.make:540: kodi-x11] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:5625: CMakeFiles/kodi.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

6451b7937d811203597f902add034710a74958ab is the first bad commit
commit 6451b7937d811203597f902add034710a74958ab
Author: 78andyp <99039295+78andyp@users.noreply.github.com>
Date:   Mon May 26 22:14:11 2025 +0100

    Fix retrieval of basepath.
    
    Looking at the existing code basepath is different to the actual path of the media file, it is where the actual physical file resides (eg. for an archive:// path the basepath is the path in which the archive file itself resides not the media contained therein which the archive:// path+file points to, and for BD file structure its the movie directory not the BDMV directory with index.BDMV).

 xbmc/filesystem/BlurayDirectory.cpp |  2 +-
 xbmc/utils/URIUtils.cpp             | 16 +++++++++++++---
 xbmc/video/VideoDatabase.cpp        |  2 +-
 3 files changed, 15 insertions(+), 5 deletions(-)
```

Comment (78andyp) [reply xbmc/utils/URIUtils.cpp:471]: Jenkins was happy with it. Let me resurrect the branch and see if it will build it manually.

Comment (78andyp) [reply xbmc/utils/URIUtils.cpp:471]: Hold on - I wonder if this is a #ifdef issue - it might need to be wrapped in #ifdef HAVE_LIBBLURAY - let me post a quick patch.

Comment (78andyp) [reply xbmc/utils/URIUtils.cpp:471]: Hi @howie-f - can you let me know if #26948 fixes it for you?? Thanks.

Comment (howie-f) [reply xbmc/utils/URIUtils.cpp:471]: yes, this works for me. Thanks for the quick response. i should have mentioned i build with `ENABLE_BLURAY=NO`

Comment (78andyp) [reply xbmc/utils/URIUtils.cpp:471]: Brilliant, thanks. Sorry - I normally try and do a manual build here (I'm on windows) but I split these little PRs out and forgot. Jenkins I think assumes libbluray is present so doesn't pick up (it happened once before).

Looking back I think copilot did notice, but the error (like above) isn't obvious - as the function is there - and I assumed it was an AI mistake - whereas it was a human one!!. I'm sure @garbear will have something to say about that!!
EDIT - although looking at it again it's complaining about somthing else:
image

Once Jenkins has finished with the fix I'll merge it.
