### ISSUE TITLE
Kodi fails to build with flatbuffers-23.5.26

### ISSUE THREAD

**Issue by yurivict** [xbmc/xbmc#23331]
### Describe the bug
```
In file included from /wrkdirs/usr/ports/multimedia/kodi/work/xbmc-20.1-Nexus/xbmc/cores/RetroPlayer/savestates/SavestateDatabase.cpp:12:
/wrkdirs/usr/ports/multimedia/kodi/work/xbmc-20.1-Nexus/xbmc/cores/RetroPlayer/savestates/SavestateFlatBuffer.h:19:7: error: definition of type 'FlatBufferBuilder' conflicts with type alias of the same name
class FlatBufferBuilder;
      ^
/usr/local/include/flatbuffers/flatbuffer_builder.h:1414:7: note: 'FlatBufferBuilder' declared here
using FlatBufferBuilder = FlatBufferBuilderImpl<false>;
      ^
1 error generated.
```

The build is expected to rebuild all flatbuffers-related sources using flatc. You can't hardcode any types related to flatbuffers because they can change with new releases of flatbuffers.

### Your Environment

xbmc-20.1-Nexus
flatbuffers-23.5.26
FreeBSD 13.2

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
Thanks for the report, the issues has been resolved on master.
