### ISSUE TITLE
Build on Win x64 seems broken (with VS 2022 17.4.0)

### ISSUE THREAD

**Issue by 78andyp** [xbmc/xbmc#22119]
Kodi x64 fails to build.

Here is a clear and concise description of what the problem is:

Have been building kodi x64 successfully for a while. Last 2-3 days fails. See error log below.
Today started from scratch and downloaded fresh installation - still fails.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi builds without errors

## Actual Behavior

Error.

### To Reproduce

1. Follow instructions in https://github.com/xbmc/xbmc/blob/master/docs/README.Windows.md
2. Fails at buildsetup
3.

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/akalikegas.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

20 beta 1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
You're going to have to try git bisect it, but looking at the errors

```
D:\Projects\kodi\lib\win32\Effects11\EffectVariable.inl(4346,37): error C2027: use of undefined type 'D3DX11Effects::SA
ssignment' [D:\Projects\kodi\kodi-build.x64\build\Effects11\effects11.vcxproj]
D:\Projects\kodi\lib\win32\Effects11\Effect.h(59,8): message : see declaration of 'D3DX11Effects::SAssignment' [D:\Proj
ects\kodi\kodi-build.x64\build\Effects11\effects11.vcxproj]
D:\Projects\kodi\lib\win32\Effects11\EffectVariable.inl(4471,37): error C2027: use of undefined type 'D3DX11Effects::SA
ssignment' [D:\Projects\kodi\kodi-build.x64\build\Effects11\effects11.vcxproj]
D:\Projects\kodi\lib\win32\Effects11\Effect.h(59,8): message : see declaration of 'D3DX11Effects::SAssignment' [D:\Proj
ects\kodi\kodi-build.x64\build\Effects11\effects11.vcxproj]
D:\Projects\kodi\lib\win32\Effects11\EffectVariable.inl(4597,37): error C2027: use of undefined type 'D3DX11Effects::SA
ssignment' [D:\Projects\kodi\kodi-build.x64\build\Effects11\effects11.vcxproj]
D:\Projects\kodi\lib\win32\Effects11\Effect.h(59,8): message : see declaration of 'D3DX11Effects::SAssignment' [D:\Proj
ects\kodi\kodi-build.x64\build\Effects11\effects11.vcxproj]
```

Theres definitely been no change in a long time for the effects lib. Im guessing something has changed with your build system in some way to cause the undefined  errors.

Just as an anecdote, ive been building tip of master the last couple days without any issues for windows x64 target using 
```
Visual Studio 2022 Developer Command Prompt v17.1.1
```

**Comment by 78andyp** [comment]
Rolling back to VS 2022 17.3.6 from VS 2022 17.4.0 fixed it.

**Comment by fuzzard** [comment]
Cool. Good to know.

I'll leave this open still as it'll obviously need to be investigated at some point.

@thexai just a heads up about potential future issues.
