### PR TITLE
DBus refactoring

### PR DESCRIPTION
**Pull request by yol**
Refactor the DBus code on Linux to use RAII and have less repetition

## Description
Introduce RAII wrappers for `DBusConnection`, `DBusMessage`, and `DBusError`. The goal is still not to provide full C++ bindings for DBus, but just to make life a bit easier and make use of C++ comfort features.
I've tried not to change Kodi's behavior regarding PM etc.

## Motivation and Context
The DBus code suffers of a great deal of copy&paste because RAII isn't used and simple helpers for common stuff were not added.
Also, `dbus_connection_close` and  `dbus_connection_unref` are potentially called on a `NULL` connection in some places which is illegal.

## How Has This Been Tested?
Compiled for X11, log output checked

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/linux/DBusUtil.cpp [hunk 1]
```diff
@@ -164,6 +164,62 @@ CVariant CDBusUtil::ParseType(DBusMessageIter *itr)
...
+  if (openPrivate)
+  {
+    m_connection.reset(dbus_bus_get_private(bus, error));
+  }
+  else
+  {
+    m_connection.reset(dbus_bus_get(bus, error));
+  }
+
+  return !!m_connection;
```
Comment (fritsch) [inline xbmc/linux/DBusUtil.cpp]: Good one - perfectly fine.

**Comment by fritsch** [comment]
Really nice. Thanks very much. Did you runtime test it?

**Comment by pkerling** [comment]
Yes and it does work so far, but I could not really test all the DeviceKit etc. stuff since my Linux does not have it any more.

**Comment by pkerling** [comment]
grr jenkins, someone rebuild this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by fritsch** [comment]
Btw. if you find stuff that is totally outdated and not used anymore by the latest LTS release 16.04 - feel free to PR its removal. If someone needs it - a revert is always a possibility.

**Comment by pkerling** [comment]
build/test failures seem unrelated

ConsoleKit is outdated, but people that don't (want to) run systemd might still use it. [ConsoleKit2](https://github.com/ConsoleKit2/ConsoleKit2) seems to be under active development and is probably compatible.
DeviceKit is dead since 2009, so there's a prime candidate for removal. 
UDisks uses a different interface (UDisks2) since 2012, so should be adapted or removed. Support for UDisks2 would be cool though, since the current fallback (udev) does not allow mount/unmount for unprivileged users.
Anyway, separate PR :)

**Comment by MartijnKaijser** [comment]
ok to merge?
indeed fails are unrelated

**Comment by tamland** [comment]
Do you need some special dependency/version for this? I can't compile anymore due to:

````bash
[ 89%] Building CXX object build/linuxsupport/CMakeFiles/linuxsupport.dir/DBusUtil.cpp.o
~/xbmc/xbmc/linux/DBusUtil.cpp:184:18: error: defaulting this default constructor would delete it after its first declaration
CDBusConnection::CDBusConnection() = default;
                 ^
~/xbmc/xbmc/linux/DBusUtil.h:69:58: note: default constructor of 'CDBusConnection' is implicitly deleted because field 'm_connection' has no default constructor
  std::unique_ptr<DBusConnection, DBusConnectionDeleter> m_connection;
                                                         ^
1 error generated.
````

**Comment by asavah** [comment]
@tamland that error seems to be caused by https://github.com/xbmc/xbmc/pull/12400
I've hit it too while croscompiling for arm with gcc 7.1

**Comment by pkerling** [comment]
The changes in #12400 seem fine to me though. Can you reproduce with clang? Maybe it's a compiler bug. Compiles fine on gcc-6.3.1 here. @tamland what compiler/version are you using?

**Comment by tamland** [comment]
Yeah, don't understand this either.. I'm using clang 4.0.1

**Comment by tamland** [comment]
It does compile if I revert this one line though: https://github.com/xbmc/xbmc/pull/12400/files#diff-3df84cc27c11292eb08a86e730844661R65

**Comment by pkerling** [comment]
Only have clang-3.9 here :-/
Maybe you can try the following: In DBusUtil.h, replace `DBusConnectionDeleter() = default;` with `DBusConnectionDeleter() noexpect = default;` - only a wild guess though. Can test with newer gcc/clang next week.

**Comment by tamland** [comment]
>Maybe you can try the following

Different error:

````
~/xbmc/xbmc/linux/DBusUtil.h:65:5: error: default member initializer for 'closeBeforeUnref' needed within definition of enclosing class 'CDBusConnection' outside of member functions
    DBusConnectionDeleter() noexcept = default;
    ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../include/c++/7.1.1/type_traits:1577:29: note: in instantiation of template class 'std::remove_volatile<CDBusConnection::DBusConnectionDeleter>' requested here
      remove_const<typename remove_volatile<_Tp>::type>::type     type;
                            ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../include/c++/7.1.1/type_traits:384:43: note: in instantiation of template class 'std::remove_cv<CDBusConnection::DBusConnectionDeleter>' requested here
    : public __is_pointer_helper<typename remove_cv<_Tp>::type>::type
                                          ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../include/c++/7.1.1/type_traits:154:39: note: in instantiation of template class 'std::is_pointer<CDBusConnection::DBusConnectionDeleter>' requested here
    : public integral_constant<bool, !_Pp::value>
                                      ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../include/c++/7.1.1/type_traits:144:26: note: in instantiation of template class 'std::__not_<std::is_pointer<CDBusConnection::DBusConnectionDeleter> >' requested here
    : public conditional<_B1::value, _B2, _B1>::type
                         ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../include/c++/7.1.1/bits/unique_ptr.h:134:9: note: in instantiation of template class 'std::__and_<std::__not_<std::is_pointer<CDBusConnection::DBusConnectionDeleter> >, std::is_default_constructible<CDBusConnection::DBusConnectionDeleter> >' requested here
        __and_<__not_<is_pointer<_Dp>>,
        ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../include/c++/7.1.1/bits/unique_ptr.h:163:33: note: in instantiation of template class 'std::__uniq_ptr_impl<DBusConnection, CDBusConnection::DBusConnectionDeleter>' requested here
      __uniq_ptr_impl<_Tp, _Dp> _M_t;
                                ^
~/xbmc/xbmc/linux/DBusUtil.h:69:58: note: in instantiation of template class 'std::unique_ptr<DBusConnection, CDBusConnection::DBusConnectionDeleter>' requested here
  std::unique_ptr<DBusConnection, DBusConnectionDeleter> m_connection;
                                                         ^
~/xbmc/xbmc/linux/DBusUtil.h:66:10: note: default member initializer declared here
    bool closeBeforeUnref = false;
         ^
1 error generated.
````

**Comment by pkerling** [comment]
*sigh* I have no idea why I should move something to the enclosing class here. Maybe moving the constructor to the implementation file will help.

I'll try to fix it tomorrow.

**Comment by candrews** [comment]
I'm also getting compilation errors using GCC 7.1 (not cross compiling) due to this PR:
```
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/7.1.0/include/g++-v7/bits/move.h:54:0,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/7.1.0/include/g++-v7/bits/stl_pair.h:59,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/7.1.0/include/g++-v7/bits/stl_algobase.h:64,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/7.1.0/include/g++-v7/memory:62,
                 from /var/tmp/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/powermanagement/PowerManager.h:23,
                 from /var/tmp/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/powermanagement/PowerManager.cpp:21:
/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.0/include/g++-v7/type_traits: In substitution of ‘template<class _Tp, class> static std::true_type std::__do_is_default_constructible_impl::__test(int) [with _Tp = CDBusConnection::DBusConnectionDeleter; <template-parameter-1-2> = <missing>]’:
/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.0/include/g++-v7/type_traits:892:35:   required from ‘struct std::__is_default_constructible_impl<CDBusConnection::DBusConnectionDeleter>’
/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.0/include/g++-v7/type_traits:143:12:   required from ‘struct std::__and_<std::__not_<std::is_void<CDBusConnection::DBusConnectionDeleter> >, std::__is_default_constructible_impl<CDBusConnection::DBusConnectionDeleter> >’
/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.0/include/g++-v7/type_traits:896:12:   required from ‘struct std::__is_default_constructible_atom<CDBusConnection::DBusConnectionDeleter>’
/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.0/include/g++-v7/type_traits:917:12:   required from ‘struct std::__is_default_constructible_safe<CDBusConnection::DBusConnectionDeleter, false>’
/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.0/include/g++-v7/type_traits:923:12:   required from ‘struct std::is_default_constructible<CDBusConnection::DBusConnectionDeleter>’
/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.0/include/g++-v7/type_traits:143:12:   required from ‘struct std::__and_<std::__not_<std::is_pointer<CDBusConnection::DBusConnectionDeleter> >, std::is_default_constructible<CDBusConnection::DBusConnectionDeleter> >’
/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.0/include/g++-v7/bits/unique_ptr.h:135:47:   required from ‘class std::__uniq_ptr_impl<DBusConnection, CDBusConnection::DBusConnectionDeleter>’
/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.0/include/g++-v7/bits/unique_ptr.h:163:33:   required from ‘class std::unique_ptr<DBusConnection, CDBusConnection::DBusConnectionDeleter>’
/var/tmp/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/linux/DBusUtil.h:69:58:   required from here
/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.0/include/g++-v7/type_traits:881:48: error: constructor required before non-static data member for ‘CDBusConnection::DBusConnectionDeleter::closeBeforeUnref’ has been parsed
     template<typename _Tp, typename = decltype(_Tp())>
```

**Comment by tamland** [comment]
I've removed the `= default` in master for now so you can compile until this is resolved (at least it compiles with clang).

**Comment by candrews** [comment]
GCC is now also works - thanks!

**Comment by hauihau** [comment]
I also ran into the issue with GCC 7.1. Looks like a GCC Bug because 6.3 is fine. The issue was reported to GCC: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81359.

**Comment by pkerling** [comment]
I do find the behavior strange, but I don't know the C++ standard well enough to really judge whether it's a compiler error or a standard corner case, or even a bug in the standard. It's very peculiar though that *both* GCC and clang start to reject the code in newer versions. Anyway, should be fixed with #12457.
