### PR TITLE
[filesystem] Switch to long for CURLPROXY_* enums

### PR DESCRIPTION
**Pull request by fossdd**
## Description / Motivation and context

curl 8.16.0 bumped the enums to long, see: https://github.com/curl/curl/pull/18054

This fixes the build with curl 8.16+ for the following failure:

	/builds/alpine/aports/community/kodi/src/xbmc-21.2-Omega/xbmc/filesystem/CurlFile.cpp:48:5: error: cannot initialize an array element of type 'curl_proxytype' with an rvalue of type 'long'
	   48 |     CURLPROXY_HTTP,   CURLPROXY_SOCKS4,          CURLPROXY_SOCKS4A,
	      |     ^~~~~~~~~~~~~~
	/usr/include/curl/curl.h:791:35: note: expanded from macro 'CURLPROXY_HTTP'
	  791 | #define CURLPROXY_HTTP            0L /* added in 7.10, new in 7.19.4 default is
	      |                                   ^~
	...

## How has this been tested?
Built on Alpine Linux with musl libc on x86_64.

## What is the effect on users?
N/A

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by bkuhls** [comment]
fyi: this is the fix for Omega: https://gitlab.alpinelinux.org/alpine/aports/-/commit/106a02411488e3f71b9f2085a4a857e4be27b9ea

**Comment by garbear** [comment]
Being that this is a compile fix, we'll take on the risk for v21. Still undecided on if there will be a v21.3, but packagers can use this to fix builds.

**Comment by garbear** [comment]
Sorry, i might have merged this prematurely. Compile time effort will tell.
