### PR TITLE
[Bluray] Fix failure to compile on linux without libbluray.

### PR DESCRIPTION
**Pull request by 78andyp**
## Description

Wrap a call to a CBlurayDirectory function in an #ifdef.
This isn't picked up by Jenkins.

## Motivation and context

Thanks to @howie-f pointing out:
```
[100%] Linking CXX executable kodi-x11
build/utils/utils.a(URIUtils.cpp.o):URIUtils.cpp:function URIUtils::GetBasePath(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&):

error: undefined reference to 'XFILE::CBlurayDirectory::GetBasePath[abi:cxx11](CURL const&)'
collect2: error: ld returned 1 exit status

gmake[2]: *** [CMakeFiles/kodi.dir/build.make:540: kodi-x11] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:5625: CMakeFiles/kodi.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

6451b7937d811203597f902add034710a74958ab is the first bad commit
commit 6451b7937d811203597f902add034710a74958ab
Author: 78andyp <99039295+78andyp@users.noreply.github.com>
Date:   Mon May 26 22:14:11 2025 +0100

    Fix retrieval of basepath.
    
    Looking at the existing code basepath is different to the actual path of the media file, it is where the actual physical file resides (eg. for an archive:// path the basepath is the path in which the archive file itself resides not the media contained therein which the archive:// path+file points to, and for BD file structure its the movie directory not the BDMV directory with index.BDMV).

 xbmc/filesystem/BlurayDirectory.cpp |  2 +-
 xbmc/utils/URIUtils.cpp             | 16 +++++++++++++---
 xbmc/video/VideoDatabase.cpp        |  2 +-
 3 files changed, 15 insertions(+), 5 deletions(-)
```

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Review by howie-f — APPROVED** [review]
:+1:
