### ISSUE TITLE
Unable to compile on Ubuntu 24.04 LTS since #28314 was merged

### ISSUE THREAD

**Issue by Gujal00** [xbmc/xbmc#28813]
### Describe the bug
Here is a clear and concise description of what the problem is:

When compiling kodi on Ubuntu 24.04 LTS, able to compile successfully until commit 2e7db58
But including commit [6085fd4](https://github.com/xbmc/xbmc/commit/6085fd4cf8ab2af325ae96b160ba3b090f0450d4) causes the compile to fail

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Successful compile

## Actual Behavior

Stops with error in the new file included in the above mentioned commit
```
In file included from /home/gujal/kodi/xbmc/music/tags/MusicInfoTagLoaderMatroska.h:12,
                 from /home/gujal/kodi/xbmc/music/tags/MusicInfoTagLoaderFactory.cpp:17:
/home/gujal/kodi/xbmc/music/tags/MatroskaTagLibStream.h:164:42: error: ‘TagLib::offset_t’ has not been declared
  164 |   void insert(const TagLib::ByteVector&, TagLib::offset_t, size_t) override {}
      |                                          ^~~~~~
/home/gujal/kodi/xbmc/music/tags/MatroskaTagLibStream.h:165:20: error: ‘TagLib::offset_t’ has not been declared
  165 |   void removeBlock(TagLib::offset_t, size_t) override {}
      |                    ^~~~~~
/home/gujal/kodi/xbmc/music/tags/MatroskaTagLibStream.h:176:13: error: ‘TagLib::offset_t’ has not been declared
  176 |   void seek(TagLib::offset_t offset, TagLib::IOStream::Position p) override
      |             ^~~~~~
/home/gujal/kodi/xbmc/music/tags/MatroskaTagLibStream.h:198:11: error: ‘offset_t’ in namespace ‘TagLib’ does not name a type
  198 |   TagLib::offset_t tell() const override { return m_virtualPos; }
      |           ^~~~~~~~
/home/gujal/kodi/xbmc/music/tags/MatroskaTagLibStream.h:200:11: error: ‘offset_t’ in namespace ‘TagLib’ does not name a type
  200 |   TagLib::offset_t length() override { return m_fileLength; }
      |           ^~~~~~~~
/home/gujal/kodi/xbmc/music/tags/MatroskaTagLibStream.h:202:17: error: ‘TagLib::offset_t’ has not been declared
  202 |   void truncate(TagLib::offset_t) override {}
      |                 ^~~~~~
/home/gujal/kodi/xbmc/music/tags/MatroskaTagLibStream.h:164:8: error: ‘void MatroskaTagLibStream::insert(const TagLib::ByteVector&, int, size_t)’ marked ‘override’, but does not override
  164 |   void insert(const TagLib::ByteVector&, TagLib::offset_t, size_t) override {}
      |        ^~~~~~
/home/gujal/kodi/xbmc/music/tags/MatroskaTagLibStream.h:165:8: error: ‘void MatroskaTagLibStream::removeBlock(int, size_t)’ marked ‘override’, but does not override
  165 |   void removeBlock(TagLib::offset_t, size_t) override {}
      |        ^~~~~~~~~~~
/home/gujal/kodi/xbmc/music/tags/MatroskaTagLibStream.h:176:8: error: ‘void MatroskaTagLibStream::seek(int, TagLib::IOStream::Position)’ marked ‘override’, but does not override
  176 |   void seek(TagLib::offset_t offset, TagLib::IOStream::Position p) override
      |        ^~~~
/home/gujal/kodi/xbmc/music/tags/MatroskaTagLibStream.h:202:8: error: ‘void MatroskaTagLibStream::truncate(int)’ marked ‘override’, but does not override
  202 |   void truncate(TagLib::offset_t) override {}
      |        ^~~~~~~~
gmake[2]: *** [build/music/tags/CMakeFiles/music_tags.dir/build.make:118: build/music/tags/CMakeFiles/music_tags.dir/MusicInfoTagLoaderFactory.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:9575: build/music/tags/CMakeFiles/music_tags.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2
```

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 24.04 LTS
 - Kodi version: master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Gujal00** [comment]
Can be closed

Works fine by adding `-DENABLE_INTERNAL_TAGLIB=ON` to cmake during the build
