### PR TITLE
Include cstddef to fix build with gcc 4.9

### PR DESCRIPTION
**Pull request by bkuhls**
## Description
Fixes build error with
  gcc version 4.9.1 (Sourcery CodeBench Lite 2014.11-95)

```
kodi/xbmc/cores/RetroPlayer/rendering/VideoRenderers/RPRendererOpenGL.cpp: In constructor 'KODI::RETRO::CRPRendererOpenGL::CRPRendererOpenGL(const KODI::RETRO::CRenderSettings&, KODI::RETRO::CRenderContext&, std::shared_ptr<KODI::RETRO::IRenderBufferPool>)':
kodi/xbmc/cores/RetroPlayer/rendering/VideoRenderers/RPRendererOpenGL.cpp:65:78: error: expected primary-expression before ',' token
                         reinterpret_cast<const GLvoid*>(offsetof(PackedVertex, x)));

kodi/xbmc/guilib/GUITextureGL.cpp: In member function 'virtual void CGUITextureGL::End()':
kodi/xbmc/guilib/GUITextureGL.cpp:118:82: error: expected primary-expression before ',' token
                             reinterpret_cast<const GLvoid*>(offsetof(PackedVertex, u2)));
```
Needed after commit: https://github.com/xbmc/xbmc/commit/cd5ff67a79287284fc88a31d0dba7f626f3c9f6a

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document

### CODE REVIEW

**Review by garbear — APPROVED** [review]
`offsetof` is defined in cstddef, so this looks correct. @lrusak?

**Review by lrusak — APPROVED** [review]
LGTM

**Comment by lrusak** [comment]
@bkuhls is this required for the GLES path also?

**Comment by bkuhls** [comment]
> 
> 
> @bkuhls is this required for the GLES path also?

No, the header is already included for GLES:
https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/GUITextureGLES.cpp#L20
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/RetroPlayer/rendering/VideoRenderers/RPRendererOpenGLES.cpp#L19

Build-test with gcc-4.9.1 and GLES was positive with one exception unrelated to this PR:
https://github.com/xbmc/xbmc/pull/18858/files/9b8f600127f033a3c606d80e5008a9e8a42c96e2#diff-1011d16c19f62909622492fc1b5eef54f5759bfe8af5523622e39569d808ff06R103

**Comment by garbear** [comment]
Right, looks like that line should be

```c++
return std::tuple<bool, uint64_t>{true, prop->enums[j].value};
```

**Comment by ksooo** [comment]
@DaveTBlake this one is good for v19.

**Comment by DaveTBlake** [comment]
Lurking lost unlablled, thanks @ksooo
