### PR TITLE
Python: allow building against Python 3.13

### PR DESCRIPTION
**Pull request by lrusak**
Fedora 41 ships with python 3.13. It currently fails to build.

https://fedoraproject.org/wiki/Releases/41/ChangeSet#Changes/Python3.13

```
home/lukas/Documents/git/xbmc/xbmc/interfaces/python/swig.cpp: In constructor ‘PythonBindings::TypeInfo::TypeInfo(const std::type_info&)’:
/home/lukas/Documents/git/xbmc/xbmc/interfaces/python/swig.cpp:78:5: error: missing initializer for member ‘_typeobject::tp_versions_used’ [-Werror=missing-field-initializers]
   78 |     };
      |     ^
```

I haven't actually runtime tested this but it builds :)

This will probably need a backport also

### CODE REVIEW

**Review by fuzzard — APPROVED** [review]

**Comment by fuzzard** [comment]
Same change I have in a branch https://github.com/fuzzard/xbmc/commit/c801cfd0b7767ffa41cb7e278d08d66ad927d242
Tested functional for macos

**Comment by fuzzard** [comment]
osx build failure will be fixed by https://github.com/xbmc/xbmc/pull/25905

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please
