### PR TITLE
Fix missing xbmcgui.ACTION_ values

### PR DESCRIPTION
**Pull request by LS80**
Adds an include of `input/ActionIDs.h` which was recently introduced in https://github.com/xbmc/xbmc/pull/11645 

## Motivation and Context

Navigation is broken in some addons due to `xbmcgui` missing all the `ACTION_` IDs such as `ACTION_MOVE_DOWN`. The log shows errors such as
```
 Error Type: <type 'exceptions.AttributeError'>
 Error Contents: 'module' object has no attribute 'ACTION_MOVE_DOWN'
```
I have no idea if this actually fixes the problem as I have been unable to compile with the new cmake system.

## How Has This Been Tested?
Not tested as I have been unable to compile with cmake.

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by MediaBrasil** [comment]
Thanks, this solve trouble..now extendeinfo work fine again.

**Comment by Rechi** [comment]
jenkins build this please

File: xbmc/interfaces/swig/AddonModuleXbmcgui.i [hunk 1]
```diff
@@ -29,6 +29,7 @@
 #include "interfaces/legacy/Dialog.h"
 #include "interfaces/legacy/WindowXML.h"
 #include "input/Key.h"
+#include "input/ActionIDs.h"
```
Comment (Rechi) [inline xbmc/interfaces/swig/AddonModuleXbmcgui.i]: please move this one line up to match our [Code guidelines for includes](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html#code_guidelines_1_3)

Comment (LS80) [inline xbmc/interfaces/swig/AddonModuleXbmcgui.i]: Done

**Comment by Rechi** [comment]
@garbear any comment

**Comment by garbear** [comment]
i'm not all that familiar with our codegen, but this looks good

**Comment by Rechi** [comment]
Tested by adding `xbmcgui.ACTION_MOVE_DOWN` to an add-on. Works again with this change.

jenkins build and merge
