### PR TITLE
[NFS] replace nfs_create with nfs_open2

### LINKED ISSUE #28164: kodi githash dc3168b fails to build: nfs_create/nfs_creat related
### Describe the bug
Here is a clear and concise description of what the problem is:

Updated kodi to githash dc3168b by creating a pull request for kodi flatpak beta branch: https://github.com/flathub/tv.kodi.Kodi/pull/677/changes/feab9101dc0347e1d0dd43bfedde6b10155f47f4

Build failed: https://github.com/flathub-infra/vorarbeiter/actions/runs/24240000676/job/70772064095

Related to: https://github.com/xbmc/xbmc/pull/28152

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Compilation was expected to succeed

## Actual Behavior

Compilation failed:
```
FAILED: [code=1] build/filesystem/CMakeFiles/filesystem.dir/NFSFile.cpp.o 
/usr/bin/ccache /run/ccache/bin/c++ -DCMS_NO_REGISTER_KEYWORD -DFFMPEG_VER_SHA=7.0.0 -DFMT_SHARED -DHAS_AIRPLAY -DHAS_AIRTUNES -DHAS_ALSA -DHAS_AVAHI -DHAS_DBUS -DHAS_EGL -DHAS_FILESYSTEM_NFS -DHAS_FILESYSTEM_SMB -DHAS_GBM_BO_MAP -DHAS_GBM_MODIFIERS -DHAS_GL -DHAS_GLX -DHAS_ISO9660PP -DHAS_LIRC -DHAS_MARIADB -DHAS_NEON -DHAS_PIPEWIRE -DHAS_PULSEAUDIO -DHAS_PYTHON -DHAS_UDFREAD -DHAS_WEB_INTERFACE -DHAS_WEB_SERVER -DHAS_ZEROCONF -DHAVE_DRM_MODIFIER_NAME -DHAVE_EGLEXTANGLE -DHAVE_GBM -DHAVE_HDR_OUTPUT_METADATA -DHAVE_LCMS2 -DHAVE_LIBBLUETOOTH -DHAVE_LIBBLURAY -DHAVE_LIBBLURAY_BDJ -DHAVE_LIBCAP -DHAVE_LIBCEC -DHAVE_LIBUDEV -DHAVE_LIBVA -DHAVE_LIBVDPAU -DHAVE_LIBXRANDR -DHAVE_LIBXSLT -DHAVE_NEW_CROSSGUID -DHAVE_WAYLAND -DHAVE_X11 -DNPT_CONFIG_ENABLE_LOGGING -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -D_FILE_OFFSET_BITS=64 -I/run/build/kodi -I/run/build/kodi/xbmc -I/run/build/kodi/xbmc/platform/linux -I/run/build/kodi/xbmc/cores/VideoPlayer -I/run/build/kodi/build -I/run/build/kodi/build/include -I/run/build/kodi/xbmc/platform/posix -isystem /usr/include/fribidi -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/include/harfbuzz -isystem /usr/include/glib-2.0 -isystem /usr/lib/aarch64-linux-gnu/glib-2.0/include -isystem /usr/include/uuid -isystem /run/build/kodi/build/cores/RetroPlayer/messages -isystem /usr/include/lzo -isystem /usr/include/taglib -isystem /usr/include/libdrm -isystem /usr/include/dbus-1.0 -isystem /usr/lib/aarch64-linux-gnu/dbus-1.0/include -isystem /usr/include/libxml2 -isystem /app/include/libcec -isystem /usr/include/p11-kit-1 -isystem /usr/include/pipewire-0.3 -isystem /usr/include/spa-0.2 -isystem /usr/include/python3.13 -isystem /app/include/mariadb -isystem /run/build/kodi/lib/libUPnP -isystem /run/build/kodi/lib/libUPnP/Platinum/Source/Core -isystem /run/build/kodi/lib/libUPnP/Platinum/Source/Platinum -isystem /run/build/kodi/lib/libUPnP/Platinum/Source/Devices/MediaConnect -isystem /run/build/kodi/lib/libUPnP/Platinum/Source/Devices/MediaRenderer -isystem /run/build/kodi/lib/libUPnP/Platinum/Source/Devices/MediaServer -isystem /run/build/kodi/lib/libUPnP/Neptune/Source/Core -isystem /run/build/kodi/lib/libUPnP/Neptune/Source/System/Posix -O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -mbranch-protection=bti+pac-ret -Wall -Wdouble-promotion -Wmissing-field-initializers -Wsign-compare -Wextra -Wno-unused-parameter -Wnon-virtual-dtor -O3 -DNDEBUG -std=c++20 -DTARGET_POSIX -DTARGET_LINUX -D_GNU_SOURCE -DHAVE_LINUX_UDMABUF=1 -DHAVE_LINUX_DMA_HEAP=1 -DHAVE_LINUX_DMA_BUF=1 -DHAVE_MKOSTEMP=1 -DHAVE_GETMNTENT_R=1 -DHAVE_LINUX_MEMFD=1 -DHAVE_STATX=1 -D__STDC_CONSTANT_MACROS -D_FILE_OFFSET_BITS=64 -DHAS_POSIX_NETWORK -DHAS_LINUX_NETWORK -DHAS_BUILTIN_SYNC_ADD_AND_FETCH=1 -DHAS_BUILTIN_SYNC_SUB_AND_FETCH=1 -DHAS_BUILTIN_SYNC_VAL_COMPARE_AND_SWAP=1 -DHAVE_INOTIFY=1 -DHAVE_POSIX_FADVISE=1 -DHAVE_LOCALTIME_R=1 -DHAVE_GMTIME_R=1 -DHAVE_INTTYPES_H=1 -DHAS_UPNP=1 -DHAS_OPTICAL_DRIVE -DHAS_CDDA_RIPPER -DBIN_INSTALL_PATH=\"/app/lib/kodi\" -DINSTALL_PATH=\"/app/share/kodi\" -Werror=double-promotion -Werror=missing-field-initializers -Werror=sign-compare -D_REENTRANT -MD -MT build/filesystem/CMakeFiles/filesystem.dir/NFSFile.cpp.o -MF build/filesystem/CMakeFiles/filesystem.dir/NFSFile.cpp.o.d -o build/filesystem/CMakeFiles/filesystem.dir/NFSFile.cpp.o -c /run/build/kodi/xbmc/filesystem/NFSFile.cpp
/run/build/kodi/xbmc/filesystem/NFSFile.cpp: In member function ‘virtual bool XFILE::CNFSFile::OpenForWrite(const CURL&, bool)’:
/run/build/kodi/xbmc/filesystem/NFSFile.cpp:946:11: error: ‘nfs_create’ was not declared in this scope; did you mean ‘nfs_creat’?
  946 |     ret = nfs_create(m_pNfsContext, filename.c_str(), O_RDWR | O_EXCL,
      |           ^~~~~~~~~~
      |           nfs_creat
[341/1887] Building CXX object build/filesystem/CMakeFiles/filesystem.dir/NFSDirectory.cpp.o
```

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by trexx**
## Description
A change introduced in https://github.com/xbmc/xbmc/pull/28152 broke builds against libnfs 6.x since the nfs_create function was removed in libnfs v6. I've changed the fix to use nfs_open2 instead which builds against libnfs 5.x and 6.x.

Since creation and opening happen atomically, a minor optimisation was made to prevent an unnecessary close and reopen of the file.

## Motivation and context
Fixes #28164 

## How has this been tested?

Successfully built a armeabi-v7a Android build against libnfs 5.0.2. And successfully copied a file across to an NFSv4 share.

Build against libnfs 6.0.2 and a test against an NFSv3 share is untested.

## What is the effect on users?
There should be no functional changes visible from a users perspective.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by trexx** [comment]
When the O_EXCL flag is missing, new files do not have permissions set correctly for some reason.

Looking at the libnfs code, it seems O_EXCL has a separate path which chmods the new file.
https://github.com/sahlberg/libnfs/blob/libnfs-5.0.2/lib/nfs_v4.c#L2532

**Review by thexai — APPROVED** [review]
LGTM.

Tested in Windows with NAS and also confirmed that files created with correct permissions:

`rw------- `

(in Windows there are no group/others permissions)
