### PR TITLE
Fix Coverity #1272226 Remove 'const' keyword from implementation

### PR DESCRIPTION
**Pull request by tobbi**
Fixes CID #1272226

I didn't compile this, but I think it should fix the above 

https://scan5.coverity.com:8443/reports.htm#v36179/p10258/g36180/fileInstanceId=74186804&defectInstanceId=22593443&mergedDefectId=1272226&eventId=22593443-0

### CODE REVIEW

**Comment by ace20022** [comment]
Since it's an interface I guess it won't compile.

jenkins build this please

**Comment by Paxxi** [comment]
I'd do the reverse, remove the const as it's not specified in the interface

**Comment by tobbi** [comment]
Seems to have compiled just fine. Do you want to merge it this way or shall I remove the const on the overriding method?

**Comment by Paxxi** [comment]
If you change the interface you will trigger this warning for every other class that inherits from this interface unless you also fix those.
Fix the inherited class and leave the interface alone.

**Comment by ksooo** [comment]
Here are the facts from real life (code):

interface: not const
<pre>
./cores/dvdplayer/DVDInputStreams/DVDInputStream.h:    virtual PVR::CPVRChannelPtr GetSelectedChannel() { return PVR::CPVRChannelPtr(); };
</pre>

implementations:
<pre>
./cores/dvdplayer/DVDInputStreams/DVDInputStreamPVRManager.h:  PVR::CPVRChannelPtr GetSelectedChannel() const;
</pre>

As there currently is only one implementation it is imo irrelevant whether the interface or the (one) existing implementation gets changed, as long as the result is consistency. ;-)

**Comment by Paxxi** [comment]
I'm wt work so I may have missed something but grepping repo showed several implementations other than pvr

**Comment by ksooo** [comment]
Well, no...

<pre>
kai@ghostrider /home/kai/src/github/ksooo/xbmc/xbmc (pvr-series-recordings)
$ grep -r "GetSelectedChannel" . | grep "\.h"
./cores/dvdplayer/DVDInputStreams/DVDInputStream.h:    virtual PVR::CPVRChannelPtr GetSelectedChannel() { return PVR::CPVRChannelPtr(); };
./cores/dvdplayer/DVDInputStreams/DVDInputStreamPVRManager.h:  PVR::CPVRChannelPtr GetSelectedChannel() const;
./epg/GUIEPGGridContainer.h:    const int GetSelectedChannel() { return m_channelCursor + m_channelOffset; }
</pre>

Last one is *not* an implementation of IChannel.

**Comment by Paxxi** [comment]
@ksooo yeah I see now that there's two classes that inherits from CDVDInputStream::IChannel, I was just searching for CDVDInputStream. Changing the interface will however changeCDVDInputStreamTV, it doesn't currently override the method but it inherits it.

Anyway, either is fine, my mistake thinking it would affect lots more than it does.

**Comment by ksooo** [comment]
@MartijnKaijser as this one can introduce subtile bugs and the fix is actually a no brainer, i suggest to include this for Isengard. Your button.

**Comment by tobbi** [comment]
I removed the const keyword from the implementation now. Should be better than removing it from the prototype.

**Comment by ksooo** [comment]
@tobbi thx.

**Comment by MilhouseVH** [comment]
Clean build on Ubuntu 15.04 - been building fine earlier in the day, now...

```
CPP     xbmc/guilib/IWindowManagerCallback.o
CPP     xbmc/guilib/JpegIO.o
CPP     xbmc/guilib/LocalizeStrings.o
CPP     xbmc/guilib/Shader.o
CPP     xbmc/guilib/StereoscopicsManager.o
DVDInputStreamPVRManager.cpp:297:16: error: prototype for ‘PVR::CPVRChannelPtr CDVDInputStreamPVRManager::GetSelectedChannel()’ does not match any in class ‘CDVDInputStreamPVRManager’
 CPVRChannelPtr CDVDInputStreamPVRManager::GetSelectedChannel()
                ^
In file included from DVDInputStreamPVRManager.cpp:22:0:
DVDInputStreamPVRManager.h:62:23: error: candidate is: PVR::CPVRChannelPtr CDVDInputStreamPVRManager::GetSelectedChannel() const
   PVR::CPVRChannelPtr GetSelectedChannel() const;
                       ^
../../../../Makefile.include:93: recipe for target 'DVDInputStreamPVRManager.o' failed
make[1]: *** [DVDInputStreamPVRManager.o] Error 1
Makefile:470: recipe for target 'xbmc/cores/dvdplayer/DVDInputStreams/DVDInputStreams.a' failed
make: *** [xbmc/cores/dvdplayer/DVDInputStreams/DVDInputStreams.a] Error 2
make: *** Waiting for unfinished jobs....
```

**Comment by tobbi** [comment]
Right, that happens when you change the method, but not the header. Sorry, stupid me!

**Comment by tobbi** [comment]
Please see #7261

**Comment by ksooo** [comment]
Stupid me, as I forgot the jenkins build before merge! I do really sorry.
