### ISSUE TITLE
Compile fails on Linux without libbluray when using -DENABLE_BLURAY=OFF. Bisected to recent commit.

### ISSUE THREAD

**Issue by bacon-cheeseburger** [xbmc/xbmc#26953]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi git master fails to compile without libbluray installed even when using -DENABLE_BLURAY=OFF. After bisecting, the offending commit was by 78andyp on July 2, 2025: 6451b7937d811203597f902add034710a74958ab
"Fix retrieval of basepath."

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Successfully compiling without libbluray.

## Actual Behavior

Fails to compile without libbluray.

## Possible Fix

Wrap the `#include filesystem/BlurayDirectory.h` in URIUtils.cpp with an `#ifdef HAVE_LIBBLURAY`.

### To Reproduce

1. If installed, temporarily uninstall libbluray-dev
2. Clone master 
3. Configure with -DENABLE_BLURAY=OFF and try compiling

### Debuglog

The debuglog can be found here:
There is no debug log because compile fails with:

In file included from /test/kodi-r68700.git+28fb9320ad-bisect/xbmc/utils/URIUtils.cpp:16:
/test/kodi-r68700.git+28fb9320ad-bisect/xbmc/filesystem/BlurayDirectory.h:18:10: fatal error: libbluray/bluray.h: No such file or directory
   18 | #include <libbluray/bluray.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian Linux (sid)
 - Kodi version: Current git master (kodi-r68700.git+28fb9320ad)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by 78andyp** [comment]
Let me know if this fixes it. Thanks.

**Comment by bacon-cheeseburger** [comment]
> Let me know if this fixes it. Thanks.

Yup, works. Thank you for quickly addressing this.

**Comment by 78andyp** [comment]
Thanks
