### ISSUE TITLE
master fails to build with FFmpeg >=5.0

### ISSUE THREAD

**Issue by marv** [xbmc/xbmc#21766]
### Describe the bug

Building against FFmpeg 5.1 fails because some deprecated APIs have been removed and some gained `const` specifiers:
```
[...]
/var/tmp/paludis/build/media-kodi-scm/work/kodi-scm/xbmc/cores/AudioEngine/Encoders/AEEncoderFFmpeg.cpp:281:13: error: 'avcodec_encode_a
udio2' was not declared in this scope; did you mean 'avcodec_encode_subtitle'?
  281 |   int ret = avcodec_encode_audio2(m_CodecCtx, pkt, frame, &got_output);
      |             ^~~~~~~~~~~~~~~~~~~~~
      |             avcodec_encode_subtitle
/var/tmp/paludis/build/media-kodi-scm/work/kodi-scm/xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.cpp: In member function 'virtual IA
E::SoundPtr ActiveAE::CActiveAE::MakeSound(const std::string&)':
/var/tmp/paludis/build/media-kodi-scm/work/kodi-scm/xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.cpp:3051:33: error: invalid conversion from 'AVInputFormat**' to 'const AVInputFormat**' [-fpermissive]
 3051 |   av_probe_input_buffer(io_ctx, &io_fmt, file.c_str(), nullptr, 0, 0);
      |                                 ^~~~~~~
      |                                 |
      |                                 AVInputFormat**
[...]
```

## Expected Behavior

The build should succeed

## Actual Behavior

The build errors out

## Possible Fix

Port to FFmpeg 5, examples:
- https://github.com/acoustid/chromaprint/pull/116
- https://github.com/gkv311/sview/commit/a255e0d402c6e576b4d0569a6a0fd206816d7954

### To Reproduce

1. Install FFmpeg >= 5.0
2. Configure kodi build using FFmpeg >= 5.0 
3. Start build

### Debuglog

The debuglog can be found here: 
[kodi-scm.log](https://github.com/xbmc/xbmc/files/9381902/kodi-scm.log)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Exherbo Linux
 - Kodi version: master branch @ 8a85a4c4d9b8ee8cbe10d8f073fcbe985b915ebb

**Comment by lrusak** [comment]
Already known and being worked on internally by the team.

Ref: https://github.com/xbmc/xbmc/pull/21248

**Comment by marv** [comment]
> Already known and being worked on internally by the team.

Cool, thanks for the info, it's good to know that's it's being worked on already!

What's the current progress? Is there already something I could test and give you feedback on?

**Comment by KjellRanda** [comment]
Same problem om Fedora 37:

/data/kodi/xbmc-20.0b1-Nexus/xbmc/cores/AudioEngine/Encoders/AEEncoderFFmpeg.cpp:281:13: error: ‘avcodec_encode_audio2’ was not declared in this scope; did you mean ‘avcodec_encode_subtitle’?
  281 |   int ret = avcodec_encode_audio2(m_CodecCtx, pkt, frame, &got_output);

rpm -qa|grep ffmpeg-
ffmpeg-libs-5.1.2-3.fc37.x86_64
ffmpeg-5.1.2-3.fc37.x86_64
ffmpeg-devel-5.1.2-3.fc37.x86_64

**Comment by lrusak** [comment]
You can enable using the internal ffmpeg with the cmake option `-DENABLE_INTERNAL_FFMPEG=ON`

Otherwise I'm closing this as it's know and there is a PR that fixes it (for v21) or you can just build with internal ffmpeg as stated above.
