### PR TITLE
[PythonInvoker] Re-add support for Python 3.5-3.6

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Restore some of the old "hack" methods to support python < 3.7 on linux platforms

## Motivation and Context
Fails to build against python 3.5/3.6 due to PyInterpreterState_Main only being introduced in 3.7
Therefore we ifdef and restore some of the old "hack" calls whilst we still support python 3.5/3.6

## How Has This Been Tested?
@howie-f - Can you just chime in and confirm if it worked for you

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by howie-f — APPROVED** [review]
works fine, thanks

**Comment by wsnipex** [comment]
I'm confused, ubuntu 18.04 has python 3.6, but seems to compile fine without this

**Comment by howie-f** [comment]
@wsnipex i just got
```
PythonInvoker.cpp:185:45: error: use of undeclared identifier 'PyInterpreterState_Main'
      PyThreadState* ts = PyThreadState_New(PyInterpreterState_Main());
                                            ^
PythonInvoker.cpp:608:54: error: use of undeclared identifier 'PyInterpreterState_Main'
    PyThreadState_Swap(PyInterpreterState_ThreadHead(PyInterpreterState_Main()));
                                                     ^
2 errors generated.
```
from my stretch chroot with `libpython3.5-dev:amd64 3.5.3-1+deb9u2`

**Comment by fuzzard** [comment]
Maybe the method was in for 3.6. as far as I could tell vstinner said he introduced it in 3.7.

The other option if it does work in 3.6, would be to drop support for 3.5 (it's eol as of last month I believe).

Would need someone to test compiling against 3.6  with alpha2 if that scenario was chosen

**Comment by wsnipex** [comment]
the PPA build on ubuntu 18.04 failed with this same error today

**Review by wsnipex — APPROVED** [review]
