### ISSUE TITLE
kodi 20.5 release fails to build on i686 and probably on arm32 too with taglib 2.0

### ISSUE THREAD

**Issue by david-geiger** [xbmc/xbmc#25802]
Hi,

On Mageia Cauldron release 20.5 fails to build on 32bit arches with taglib 2.0, with the following build issue:

> In file included from /home/iurt/rpmbuild/BUILD/xbmc-20.5-Nexus/xbmc/music/tags/TagLoaderTagLib.cpp:51:
/home/iurt/rpmbuild/BUILD/xbmc-20.5-Nexus/xbmc/music/tags/TagLibVFSStream.h:41:24: error: 'TagLib::ByteVector MUSIC_INFO::TagLibVFSStream::readBlock(long unsigned int)' marked 'override', but does not override
   41 |     TagLib::ByteVector readBlock(unsigned long length) override;
      |                        ^~~~~~~~~
/home/iurt/rpmbuild/BUILD/xbmc-20.5-Nexus/xbmc/music/tags/TagLibVFSStream.h:102:10: error: 'void MUSIC_INFO::TagLibVFSStream::seek(long int, TagLib::IOStream::Position)' marked 'override', but does not override
  102 |     void seek(long offset, TagLib::IOStream::Position p = Beginning) override;
      |          ^~~~
/home/iurt/rpmbuild/BUILD/xbmc-20.5-Nexus/xbmc/music/tags/TagLibVFSStream.h:112:10: error: conflicting return type specified for 'virtual long int MUSIC_INFO::TagLibVFSStream::tell() const'
  112 |     long tell() const override;

Regards,
David

Attached full build log:
[build.i686.0.20241004115014.log](https://github.com/user-attachments/files/17287018/build.i686.0.20241004115014.log)

**Comment by fuzzard** [comment]
20.x series is no longer supported

**Comment by david-geiger** [comment]
Tried latest kodi 21.1-Omega and there is the same build issue:

> In file included from /home/iurt/rpmbuild/BUILD/xbmc-21.1-Omega/xbmc/music/tags/TagLibVFSStream.cpp:8:
/home/iurt/rpmbuild/BUILD/xbmc-21.1-Omega/xbmc/music/tags/TagLibVFSStream.h:41:24: error: 'TagLib::ByteVector MUSIC_INFO::TagLibVFSStream::readBlock(long unsigned int)' marked 'override', but does not override
   41 |     TagLib::ByteVector readBlock(unsigned long length) override;
      |                        ^~~~~~~~~
/home/iurt/rpmbuild/BUILD/xbmc-21.1-Omega/xbmc/music/tags/TagLibVFSStream.h:102:10: error: 'void MUSIC_INFO::TagLibVFSStream::seek(long int, TagLib::IOStream::Position)' marked 'override', but does not override
  102 |     void seek(long offset, TagLib::IOStream::Position p = Beginning) override;
      |          ^~~~
/home/iurt/rpmbuild/BUILD/xbmc-21.1-Omega/xbmc/music/tags/TagLibVFSStream.h:112:10: error: conflicting return type specified for 'virtual long int MUSIC_INFO::TagLibVFSStream::tell() const'
  112 |     long tell() const override;
      |          ^~~~
In file included from /home/iurt/rpmbuild/BUILD/xbmc-21.1-Omega/xbmc/music/tags/TagLibVFSStream.h:14:
/usr/include/taglib/tiostream.h:156:22: note: overridden function is 'virtual TagLib::offset_t TagLib::IOStream::tell() const'
  156 |     virtual offset_t tell() const = 0;
      |                      ^~~~
/home/iurt/rpmbuild/BUILD/xbmc-21.1-Omega/xbmc/music/tags/TagLibVFSStream.h:117:10: error: conflicting return type specified for 'virtual long int MUSIC_INFO::TagLibVFSStream::length()'
  117 |     long length() override;
      |          ^~~~~~
/usr/include/taglib/tiostream.h:161:22: note: overridden function is 'virtual TagLib::offset_t TagLib::IOStream::length()'
  161 |     virtual offset_t length() = 0;
      |                      ^~~~~~
/home/iurt/rpmbuild/BUILD/xbmc-21.1-Omega/xbmc/music/tags/TagLibVFSStream.h:122:10: error: 'void MUSIC_INFO::TagLibVFSStream::truncate(long int)' marked 'override', but does not override
  122 |     void truncate(long length) override;
