### PR TITLE
[linux] fix drm object build with gcc-4.9

### PR DESCRIPTION
**Pull request by bkuhls**
## Description
Fixes build error introduced by PR 18858

```
kodi/xbmc/windowing/gbm/drm/DRMObject.cpp: In member function 'std::tuple<bool, long unsigned int> KODI::WINDOWING::GBM::CDRMObject::GetPropertyValue(const string&, const string&) const':
kodi/xbmc/windowing/gbm/drm/DRMObject.cpp:103:39: error: converting to 'std::tuple<bool, long unsigned int>' from initializer list would use explicit constructor 'constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = bool; _U2 = long long unsigned int&; <template-parameter-2-3> = void; _T1 = bool; _T2 = long unsigned int]'
     return {true, prop->enums[j].value};
```
Fix was suggested by garbear: https://github.com/xbmc/xbmc/pull/19015#issuecomment-753724865

## How Has This Been Tested?
build-tested using gcc version 4.9.1 (Sourcery CodeBench Lite 2014.11-95) 

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document

### CODE REVIEW

File: xbmc/windowing/gbm/drm/DRMObject.cpp [hunk 1]
```diff
@@ -100,7 +100,7 @@ std::tuple<bool, uint64_t> CDRMObject::GetPropertyValue(const std::string& name,
     if (prop->enums[j].name != valueName)
       continue;
 
-    return {true, prop->enums[j].value};
+    return std::tuple<bool, uint64_t>{true, prop->enums[j].value};
```
Comment (lrusak) [inline xbmc/windowing/gbm/drm/DRMObject.cpp:103]: #
```suggestion
    return std::make_tuple(true, prop->enums[j].value);
```

**Review by lrusak — CHANGES_REQUESTED** [review]
please use `std::make_tuple`

File: xbmc/windowing/gbm/drm/DRMObject.cpp (hunk 1 above)
Comment (bkuhls) [reply xbmc/windowing/gbm/drm/DRMObject.cpp]: done

**Comment by bkuhls** [comment]
@lrusak Please kick-off a new Jenkins cycle, I broke it by force-pushing too fast, sorry.

**Comment by lrusak** [comment]
jenkins build this please

**Review by garbear — APPROVED** [review]

**Comment by bkuhls** [comment]
@DaveTBlake Another candidate for v19?

**Comment by bkuhls** [comment]
rebased for master

**Comment by DaveTBlake** [comment]
Sorry @bkuhls this was over looked for the v19.0 release, lacking labels and lurking from Jan.

@lrusak happy with this now? As a fix any reason not to backport to Matrix for 19.1?

**Review by lrusak — APPROVED** [review]

**Comment by lrusak** [comment]
> Sorry @bkuhls this was over looked for the v19.0 release, lacking labels and lurking from Jan.
> 
> @lrusak happy with this now? As a fix any reason not to backport to Matrix for 19.1?

LGTM
