### ISSUE TITLE
21.3: build failure with giflib 6.1.2

### ISSUE THREAD

**Issue by tgurr** [xbmc/xbmc#28023]
## Expected Behavior
No build failure.

## Actual Behavior
Build failure:

```
[...]
[  1%] Building CXX object build/texturepacker/CMakeFiles/TexturePacker.dir/decoder/GifHelper.cpp.o
cd /var/tmp/paludis/build/media-kodi-21.3/work/build/build/texturepacker && /usr/bin/x86_64-pc-linux-gnu-c++ -DHAS_BUILTIN_SYNC_ADD_AND_FETCH=1 -DHAS_BUILTIN_SYNC_SUB_AND_FETCH=1 -DHAS_BUILTIN_SYNC_VAL_COMPARE_AND_SWAP=1 -DHAS_LINUX_NETWORK -DHAS_POSIX_NETWORK -DHAVE_GETMNTENT_R=1 -DHAVE_GMTIME_R=1 -DHAVE_INOTIFY=1 -DHAVE_INTTYPES_H=1 -DHAVE_LINUX_DMA_BUF=1 -DHAVE_LINUX_DMA_HEAP=1 -DHAVE_LINUX_MEMFD=1 -DHAVE_LINUX_UDMABUF=1 -DHAVE_LOCALTIME_R=1 -DHAVE_MKOSTEMP=1 -DHAVE_POSIX_FADVISE=1 -DHAVE_SSE2=1 -DHAVE_SSE3=1 -DHAVE_SSE4_1=1 -DHAVE_SSE=1 -DHAVE_SSSE3=1 -DHAVE_STATX=1 -DTARGET_LINUX -DTARGET_POSIX -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -I/var/tmp/paludis/build/media-kodi-21.3/work/xbmc-21.3-Omega/xbmc -I/var/tmp/paludis/build/media-kodi-21.3/work/xbmc-21.3-Omega/tools/depends/native/TexturePacker/src -I/var/tmp/paludis/build/media-kodi-21.3/work/xbmc-21.3-Omega/tools/depends/native/TexturePacker/src/decoder -march=native -O2 -pipe -Wall -Wdouble-promotion -Wmissing-field-initializers -Wsign-compare -Wextra -Wno-unused-parameter -Wnon-virtual-dtor -std=c++17 -fdiagnostics-color=always -MD -MT build/texturepacker/CMakeFiles/TexturePacker.dir/decoder/GifHelper.cpp.o -MF CMakeFiles/TexturePacker.dir/decoder/GifHelper.cpp.o.d -o CMakeFiles/TexturePacker.dir/decoder/GifHelper.cpp.o -c /var/tmp/paludis/build/media-kodi-21.3/work/xbmc-21.3-Omega/tools/depends/native/TexturePacker/src/decoder/GifHelper.cpp

Error:
  * In program cave perform install --hooks --managed-output --output-exclusivity with-others =media/kodi-21.3:0::media --destination installed --replacing =media/kodi-21.3:0::installed --x-of-y 1 of 1:
  * When installing 'media/kodi-21.3:0::media' replacing { 'media/kodi-21.3:0::installed' }:
  * When running an ebuild command on 'media/kodi-21.3:0::media':
  * Install failed for 'media/kodi-21.3:0::media' (paludis::ActionFailedError)

make[2]: Leaving directory '/var/tmp/paludis/build/media-kodi-21.3/work/build'
make[1]: Leaving directory '/var/tmp/paludis/build/media-kodi-21.3/work/build'

/var/tmp/paludis/build/media-kodi-21.3/work/xbmc-21.3-Omega/tools/depends/native/TexturePacker/src/decoder/GifHelper.cpp: In member function 'bool GifHelper::Open(GifFileType*&, void*, InputFunc)':
/var/tmp/paludis/build/media-kodi-21.3/work/xbmc-21.3-Omega/tools/depends/native/TexturePacker/src/decoder/GifHelper.cpp:58:17: error: too few arguments to function 'GifFileType* DGifOpen(void*, InputFunc, int*)'
   58 |   gif = DGifOpen(dataPtr, readFunc);
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~
In file included from /var/tmp/paludis/build/media-kodi-21.3/work/xbmc-21.3-Omega/tools/depends/native/TexturePacker/src/decoder/GifHelper.h:23,
                 from /var/tmp/paludis/build/media-kodi-21.3/work/xbmc-21.3-Omega/tools/depends/native/TexturePacker/src/decoder/GifHelper.cpp:21:
/usr/x86_64-pc-linux-gnu/include/gif_lib.h:179:14: note: declared here
  179 | GifFileType *DGifOpen(void *userPtr, InputFunc readFunc,
      |              ^~~~~~~~
/var/tmp/paludis/build/media-kodi-21.3/work/xbmc-21.3-Omega/tools/depends/native/TexturePacker/src/decoder/GifHelper.cpp:60:11: error: 'GifLastError' was not declared in this scope
   60 |     err = GifLastError();
      |           ^~~~~~~~~~~~
/var/tmp/paludis/build/media-kodi-21.3/work/xbmc-21.3-Omega/tools/depends/native/TexturePacker/src/decoder/GifHelper.cpp: In member function 'void GifHelper::Close(GifFileType*)':
/var/tmp/paludis/build/media-kodi-21.3/work/xbmc-21.3-Omega/tools/depends/native/TexturePacker/src/decoder/GifHelper.cpp:79:22: error: too few arguments to function 'int DGifCloseFile(GifFileType*, int*)'
   79 |   err = DGifCloseFile(gif);
      |         ~~~~~~~~~~~~~^~~~~
/usr/x86_64-pc-linux-gnu/include/gif_lib.h:181:5: note: declared here
  181 | int DGifCloseFile(GifFileType *GifFile, int *ErrorCode);
      |     ^~~~~~~~~~~~~
/var/tmp/paludis/build/media-kodi-21.3/work/xbmc-21.3-Omega/tools/depends/native/TexturePacker/src/decoder/GifHelper.cpp: In member function 'bool GifHelper::Slurp(GifFileType*)':
/var/tmp/paludis/build/media-kodi-21.3/work/xbmc-21.3-Omega/tools/depends/native/TexturePacker/src/decoder/GifHelper.cpp:187:14: error: 'GifLastError' was not declared in this scope
  187 |     reason = GifLastError();
      |              ^~~~~~~~~~~~
make[2]: *** [build/texturepacker/CMakeFiles/TexturePacker.dir/build.make:149: build/texturepacker/CMakeFiles/TexturePacker.dir/decoder/GifHelper.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6878: build/texturepacker/CMakeFiles/TexturePacker.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

## Possible Fix
Patch to work with giflib 6.1.2

### To Reproduce
1. Install giflib 6.1.2
2. Try to build kodi 21.3

### Debuglog
Full build log: [kodi-21.3_build.log](https://github.com/user-attachments/files/26018855/kodi-21.3_build.log)

### Screenshots 
None

## Additional context or screenshots (if appropriate)
None

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Exherbo Linux
 - Kodi version: 21.3

**Comment by tgurr** [comment]
> Thank you for using Kodi and our issue tracker. This is your friendly Kodi GitHub bot 😉
> 
> It seems that you have not followed the template we provide and require for all bug reports (or have opened a roadmap item by accident). Please understand that following the template is _mandatory_ and required for the team to be able handle the volume of open issues efficiently.
> 
> Please edit your issue message to follow our [template](https://github.com/xbmc/xbmc/blob/master/.github/ISSUE_TEMPLATE.md) and make sure to fill in all fields appropriately. The issue will be closed after one week has passed without satisfactory follow-up from your side.
> 
> This is an automatically generated message. If you believe it was sent in error, please say so and a team member will remove the "Ignored rules" label.

Not sure where I failed to follow the template 🤷

**Comment by fuzzard** [comment]
You can backport for your needs https://github.com/xbmc/xbmc/pull/28016

I dont believe theres been any consensus regarding a future 21 release, so i wouldnt hold your breathe on that front.

**Comment by tgurr** [comment]
> You can backport for your needs [#28016](https://github.com/xbmc/xbmc/pull/28016)
> 
> I dont believe theres been any consensus regarding a future 21 release, so i wouldnt hold your breathe on that front.

Thanks for the pointer to the existing PR that I somehow missed, sorry for that. Backporting is fine.

**Comment by neo1973** [comment]
Issue is fixed on master, no plans for backport to Kodi 21.
