### PR TITLE
[linux/threads] define gettid for glibc < 2.30 (fixes #21208)

### LINKED ISSUE #21208: Recent commit may have broke building on raspbian
### Describe the bug
Here is a clear and concise description of what the problem is:

The commit a5d17f691212e93d0a1eeadfd3b8fe19d1237fee changed how gettid is called on linux. Building natively on raspbian (arm) errors out on file xbmc/platform/linux/threads/ThreadImplLinux.cpp

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi is built without compilation error.

## Actual Behavior

Build errors out because gettid() is not defined.

## Possible Fix

I reverted the change in my build and that fixed the issue. But probably someone knowledgable about the platform should look more into it.

### To Reproduce

1. Cloned repo about at the time of this post 09a30d920af6ac2d8f624f243a1d6e6f23b28749
2. Built from cmake

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux / Raspbian Buster
 - Kodi version: 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by wsnipex**
## Description

building with glibc < 2.30  and ulibc is broken since a5d17f691212e93d0a1eeadfd3b8fe19d1237fee

## Motivation and context

fix build with older glibcs, e.g. on ubuntu 18.04

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
Should only need to be implemented in the cpp file

**Comment by bkuhls** [comment]
This PR also fixes uClibc builds, thanks!
