### PR TITLE
[Music]Refactor Artist/Album Information Dialog

### PR DESCRIPTION
**Pull request by DaveTBlake**
Refactor artist/album Info dialog:
- Move data read and write off the main thread to avoid possibility of locking UI.
- Support selection of any type of art.
- Correctly update the artwork for the currently playing song if the related album or artist art changes.
- Improve artist discography list to always show all the albums in the music library by that artist, and then any additional titles scraped from online sources.
- Clear local images from cache prior to image selection in attempt to immediately  show any recent external changes made to the contents of the file.

This is a follow-on from #13533 that improved the song info dialog, and some further minor enhancements (lessons learned) have also been added to that dialog too. Much of the initial explanation for that PR applies here too.

### CODE REVIEW

File: xbmc/music/dialogs/GUIDialogMusicInfo.cpp [hunk 1]
```diff
@@ -19,49 +19,315 @@
...
+      if (!database.GetArtist(artistId, artist))
+        return false;
+      tag.SetArtist(artist);
+      CMusicDatabase::SetPropertiesFromArtist(*m_item, artist);
+      m_item->SetLabel(artist.strArtist);
+
+      // Get artist folder where local art could be found
+      // Get the *name* of the folder for this artist within the Artist Info folder (may not exist).
+      // If there is no Artist Info folder specified in settings this will be blank
+      bool artistpathfound = database.GetArtistPath(artist, artist.strPath);
```
Comment (Rechi) [inline xbmc/music/dialogs/GUIDialogMusicInfo.cpp]: unused

**Comment by zag2me** [comment]
This is great, suddenly all kinds of crazy views are now possible with the music library :)

Can't wait for this to get merged so I can fill in the gaps! Already did some tests with Artwork Beef, but manual control will be very nice.

image1

image1 1

Off topic but Kodi's scaling method looks quite jagged.

**Comment by DaveTBlake** [comment]
This has some +1 for the features, and has had some user testing too, but is due a code review if anyone has a spare moment.

File: xbmc/music/MusicUtils.cpp [hunk 2]
```diff
@@ -50,19 +55,100 @@ namespace MUSIC_UTILS
...
+      else
+        db.RemoveArtForItem(itemID, type, m_artType);
+     
+      /* Update the art of the songs of the current music playlist.
+      Song thumb is often a fallback from the album and fanart is from the artist(s).
+      Clear the art if it is a song from the album or by the artist 
+      (as song or album artist) that has modified artwork. The new artwork gets
+      loaded when the playlist is shown.
+      */      
+      int iCurrentSong = -1;
```
Comment (Rechi) [inline xbmc/music/MusicUtils.cpp]: unused variable

File: xbmc/music/MusicUtils.cpp [hunk 3]
```diff
@@ -50,19 +55,100 @@ namespace MUSIC_UTILS
...
+      if (g_application.GetAppPlayer().IsPlayingAudio() &&
+        CServiceBroker::GetPlaylistPlayer().GetCurrentPlaylist() == PLAYLIST_MUSIC)
+        int iCurrentSong = CServiceBroker::GetPlaylistPlayer().GetCurrentSong();
```
Comment (Rechi) [inline xbmc/music/MusicUtils.cpp]: unused variable

**Comment by DaveTBlake** [comment]
Not sure why win64 is showing  errors when built separately it is fine? 
What is
fatal error C1090: PDB API call failed, error code '23'
