### PR TITLE
DVDVideoCodecAmlogic: remove dead code

### PR DESCRIPTION
**Pull request by stefansaraev**
## Description

remove dead code

## Motivation and Context

fixes a linux/amlogic build failure after #11417:
```
build/cores/VideoPlayer/codecs/video/dvdvideocodecs.a(DVDVideoCodecAmlogic.cpp.o): In function `CDVDVideoCodecAmlogic::Dispose()':
DVDVideoCodecAmlogic.cpp:(.text+0xd74): undefined reference to `CBitstreamParser::~CBitstreamParser()'
```

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

cc @peak3d

### CODE REVIEW

**Comment by peak3d** [comment]
@stefansaraev this PR makes everyones (kodi / mine / LE) life harder as it already is.
You know that he AML freerun patch comes soon and will conflict with this one.

**Comment by stefansaraev** [comment]
up to you to fix the build failure then.

**Comment by stefansaraev** [comment]
@peak3d well, as we dont know when you plan to PR your freerun or whatever stuff, do you have any suggestion how to "properly" fix the build issue in the meantime?

**Comment by peak3d** [comment]
@stefansaraev thanks for figuring out this issue!

https://github.com/xbmc/xbmc/pull/11588
