### PR TITLE
SavestateFlatBuffer: Remove forward declararion of FlatBufferBuilder

### LINKED ISSUE #23331: Kodi fails to build with flatbuffers-23.5.26
### Describe the bug
```
In file included from /wrkdirs/usr/ports/multimedia/kodi/work/xbmc-20.1-Nexus/xbmc/cores/RetroPlayer/savestates/SavestateDatabase.cpp:12:
/wrkdirs/usr/ports/multimedia/kodi/work/xbmc-20.1-Nexus/xbmc/cores/RetroPlayer/savestates/SavestateFlatBuffer.h:19:7: error: definition of type 'FlatBufferBuilder' conflicts with type alias of the same name
class FlatBufferBuilder;
      ^
/usr/local/include/flatbuffers/flatbuffer_builder.h:1414:7: note: 'FlatBufferBuilder' declared here
using FlatBufferBuilder = FlatBufferBuilderImpl<false>;
      ^
1 error generated.
```

The build is expected to rebuild all flatbuffers-related sources using flatc. You can't hardcode any types related to flatbuffers because they can change with new releases of flatbuffers.

### Your Environment

xbmc-20.1-Nexus
flatbuffers-23.5.26
FreeBSD 13.2

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by neo1973**
## Description
This forward declaration causes a compiler error with recent faltbuffers because the type changed:

```
In file included from xbmc/cores/RetroPlayer/savestates/SavestateDatabase.cpp:12: xbmc/cores/RetroPlayer/savestates/SavestateFlatBuffer.h:19:7: error: definition of type 'FlatBufferBuilder' conflicts with type alias of the same name
class FlatBufferBuilder;
      ^
/usr/include/flatbuffers/flatbuffer_builder.h:1414:7: note: 'FlatBufferBuilder' declared here
using FlatBufferBuilder = FlatBufferBuilderImpl<false>;
      ^
1 error generated.
```

## Motivation and context
Fix compilation, see #23331.

## How has this been tested?
It compiles with new flatbuffers 23.5.26 on my machine. If it still builds with old flattbuffers Jenkins will find out.

## What is the effect on users?
None.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Review by garbear — APPROVED** [review]
I see that flatbuffers.h is included prior so the forward declare is not needed.

**Comment by garbear** [comment]
@neo1973 Can you backport? I keep RetroPlayer in sync with master so that I can do large building on a stable v20 base.
