### PR TITLE
[cmake] Add FindMDNSEmbedded module (for Zeroconf on Android)

### PR DESCRIPTION
**Pull request by fetzerch**
## Description
Zeroconf is not available on androd. It uses mDNSEmbedded which got forgotten when migrating to cmake.

@ping: @MartijnKaijser, @wsnipex, @hudokkow 

## Motivation and Context
Zeroconf for droids.

## How Has This Been Tested?

Compile tested.

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fetzerch** [comment]
jenkins build this please

File: project/cmake/modules/FindMDNSEmbedded.cmake [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+find_library(MDNSEMBEDDED_LIBRARY NAMES mDNSEmbedded)
+
+include(FindPackageHandleStandardArgs)
+find_package_handle_standard_args(mDNSEmbedded
+                                  REQUIRED_VARS MDNSEMBEDDED_LIBRARY MDNSEMBEDDED_INCLUDE_DIR)
+
+if(MDNSEMBEDDED_FOUND)
+  set(MDNSEMBEDDED_INCLUDE_DIRS ${MDNSEMBEDDED_INCLUDE_DIR})
+  set(MDNSEMBEDDED_LIBRARIES ${MDNSEMBEDDED_LIBRARY})
+  set(MDNSEMBEDDED_DEFINITIONS -DHAVE_LIBMDNSEMBEDDED=1)
```
Comment (hudokkow) [inline project/cmake/modules/FindMDNSEmbedded.cmake]: From https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html#find-modules
> Xxx_DEFINITIONS
    Definitions to use when compiling code that uses Xxx. This really shouldn’t include options such as -DHAS_JPEG that a client source-code file uses to decide whether to #include <jpeg.h>

Is it really needed?
Otherwise looks good.

**Comment by fetzerch** [comment]
Unfortunately there are some undefined symbols now on android which got introduced by https://github.com/xbmc/xbmc/pull/10025. Guess that just slipped in because we didn't use the lib on android since we moved to cmake. Any idea how to fix or whom to ping? (@Rechi, @Memphiz.)

```
[100%] Linking CXX shared library libkodi.so
mDNSCore/mDNS.c:8688: error: undefined reference to 'FreeAnonInfo'
mDNSCore/mDNS.c:4386: error: undefined reference to 'FreeAnonInfo'
mDNSCore/mDNS.c:11945: error: undefined reference to 'FreeAnonInfo'
mDNSCore/mDNS.c:13157: error: undefined reference to 'FreeAnonInfo'
mDNSCore/mDNS.c:13137: error: undefined reference to 'AllocateAnonInfo'
mDNSCore/mDNS.c:13145: error: undefined reference to 'AllocateAnonInfo'
mDNSCore/mDNS.c:7271: error: undefined reference to 'InitializeAnonInfoForQuestion'
mDNSCore/mDNS.c:7318: error: undefined reference to 'SetAnonData'
mDNSCore/mDNS.c:9159: error: undefined reference to 'InitializeAnonInfoForCR'
mDNSCore/mDNS.c:8544: error: undefined reference to 'IdenticalAnonInfo'
mDNSCore/mDNS.c:9232: error: undefined reference to 'CopyAnonInfoForCR'
mDNSCore/mDNS.c:12069: error: undefined reference to 'AllocateAnonInfo'
mDNSCore/mDNS.c:12957: error: undefined reference to 'ReInitAnonInfo'
mDNSCore/mDNS.c:12970: error: undefined reference to 'ReInitAnonInfo'
mDNSCore/DNSCommon.c:1907: error: undefined reference to 'AnonInfoAnswersQuestion'
mDNSCore/DNSCommon.c:1941: error: undefined reference to 'AnonInfoAnswersQuestion'
mDNSCore/DNSCommon.c:1820: error: undefined reference to 'AnonInfoAnswersQuestion'
```

I'll fix the compile errors on non droid platforms (probably there's some wrong with conditionally compiling it in).

**Comment by Rechi** [comment]
@fetzerch maybe https://github.com/Rechi/xbmc/commit/10feb8e16feaaf03fa2201dfb7c23e88767910db fixes the issue, but I have no android built environment to test.

**Comment by fetzerch** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
What do you mean you didn't use the lib since the cmake move? Zeroconf was broken for android since then?

**Comment by fetzerch** [comment]
Yep. Seems no one noticed until yesterday.

**Comment by fetzerch** [comment]
jenkins build this please

**Comment by fetzerch** [comment]
Builds are fine now.
@MartijnKaijser: Could you give http://mirrors.kodi.tv/test-builds/android/arm/kodi-20161222-f22c6ec-cmake_mdns-armeabi-v7a.apk a try please?

**Comment by fetzerch** [comment]
> @fetzerch maybe Rechi@10feb8e fixes the issue, but I have no android built environment to test.

@Rechi thanks, that seems to do the trick

**Comment by MartijnKaijser** [comment]
@fetzerch seems to work.
