### ISSUE TITLE
Can't build kodi on Ubuntu 24.04.2 LTS

### ISSUE THREAD

**Issue by drelephant** [xbmc/xbmc#26904]
## Bug report

Can't finish build on Ubuntu 24.04.2 LTS

### Describe the bug
Here is a clear and concise description of what the problem is:

I'm new to building software from source but because there is now no Ubuntu PPA, I tried to build by following the [ubuntu build instructions](https://github.com/xbmc/xbmc/blob/master/docs/README.Ubuntu.md) and then the [general linux build guide](https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md), and it almost finishes (gets to [100%] Built target legacy_interface), but it gets some kind of mysql error at the end.

I have done a `git pull` in `~/kodi` folder and it says "already up to date".

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The build is successful and everyone is happy.

## Actual Behavior

`cmake ../kodi -DENABLE_INTERNAL_FFMPEG=ON -DCMAKE_INSTALL_PREFIX=/usr/local -DCORE_PLATFORM_NAME=x11 -DAPP_RENDER_SYSTEM=gl`

`cmake --build . -- VERBOSE=1 -j$(getconf _NPROCESSORS_ONLN)`

```
<snipped ~2300 lines>

[100%] Built target legacy_interface
In file included from /usr/include/mysql/mysql.h:84,
                 from /home/redacted/kodi/xbmc/dbwrappers/mysqldataset.cpp:28:
/usr/include/mysql/client_plugin.h:116:8: error: using typedef-name ‘using MYSQL = struct st_mysql’ after ‘struct’
  116 | struct MYSQL;
      |        ^~~~~
In file included from /home/redacted/kodi/xbmc/dbwrappers/mysqldataset.cpp:9:
/home/redacted/kodi/xbmc/dbwrappers/mysqldataset.h:16:7: note: ‘using MYSQL = struct st_mysql’ has a previous declaration here
   16 | using MYSQL = st_mysql;
      |       ^~~~~
/usr/include/mysql/client_plugin.h:123:58: error: using typedef-name ‘using MYSQL = struct st_mysql’ after ‘struct’
  123 |   int (*authenticate_user)(MYSQL_PLUGIN_VIO *vio, struct MYSQL *mysql);
      |                                                          ^~~~~
/home/redacted/kodi/xbmc/dbwrappers/mysqldataset.h:16:7: note: ‘using MYSQL = struct st_mysql’ has a previous declaration here
   16 | using MYSQL = st_mysql;
      |       ^~~~~
/usr/include/mysql/client_plugin.h:125:65: error: using typedef-name ‘using MYSQL = struct st_mysql’ after ‘struct’
  125 |                                                          struct MYSQL *mysql,
      |                                                                 ^~~~~
/home/redacted/kodi/xbmc/dbwrappers/mysqldataset.h:16:7: note: ‘using MYSQL = struct st_mysql’ has a previous declaration here
   16 | using MYSQL = st_mysql;
      |       ^~~~~
/usr/include/mysql/client_plugin.h:147:57: error: using typedef-name ‘using MYSQL = struct st_mysql’ after ‘struct’
  147 | struct st_mysql_client_plugin *mysql_load_plugin(struct MYSQL *mysql,
      |                                                         ^~~~~
/home/redacted/kodi/xbmc/dbwrappers/mysqldataset.h:16:7: note: ‘using MYSQL = struct st_mysql’ has a previous declaration here
   16 | using MYSQL = st_mysql;
      |       ^~~~~
/usr/include/mysql/client_plugin.h:167:59: error: using typedef-name ‘using MYSQL = struct st_mysql’ after ‘struct’
  167 | struct st_mysql_client_plugin *mysql_load_plugin_v(struct MYSQL *mysql,
      |                                                           ^~~~~
/home/redacted/kodi/xbmc/dbwrappers/mysqldataset.h:16:7: note: ‘using MYSQL = struct st_mysql’ has a previous declaration here
   16 | using MYSQL = st_mysql;
      |       ^~~~~
/usr/include/mysql/client_plugin.h:181:64: error: using typedef-name ‘using MYSQL = struct st_mysql’ after ‘struct’
  181 | struct st_mysql_client_plugin *mysql_client_find_plugin(struct MYSQL *mysql,
      |                                                                ^~~~~
/home/redacted/kodi/xbmc/dbwrappers/mysqldataset.h:16:7: note: ‘using MYSQL = struct st_mysql’ has a previous declaration here
   16 | using MYSQL = st_mysql;
      |       ^~~~~
/usr/include/mysql/client_plugin.h:200:12: error: using typedef-name ‘using MYSQL = struct st_mysql’ after ‘struct’
  200 |     struct MYSQL *mysql, struct st_mysql_client_plugin *plugin);
      |            ^~~~~
/home/redacted/kodi/xbmc/dbwrappers/mysqldataset.h:16:7: note: ‘using MYSQL = struct st_mysql’ has a previous declaration here
   16 | using MYSQL = st_mysql;
      |       ^~~~~
/usr/include/mysql/mysql.h:299:16: error: using typedef-name ‘using MYSQL = struct st_mysql’ after ‘struct’
  299 | typedef struct MYSQL {
      |                ^~~~~
/home/redacted/kodi/xbmc/dbwrappers/mysqldataset.h:16:7: note: ‘using MYSQL = struct st_mysql’ has a previous declaration here
   16 | using MYSQL = st_mysql;
      |       ^~~~~
/usr/include/mysql/mysql.h:337:3: error: conflicting declaration ‘typedef int MYSQL’
  337 | } MYSQL;
      |   ^~~~~
/home/redacted/kodi/xbmc/dbwrappers/mysqldataset.h:16:7: note: previous declaration as ‘using MYSQL = struct st_mysql’
   16 | using MYSQL = st_mysql;
      |       ^~~~~
/home/redacted/kodi/xbmc/dbwrappers/mysqldataset.cpp: In member function ‘virtual int dbiplus::MysqlDatabase::connect(bool)’:
/home/redacted/kodi/xbmc/dbwrappers/mysqldataset.cpp:183:20: warning: ‘bool mysql_ssl_set(MYSQL*, const char*, const char*, const char*, const char*, const char*)’ is deprecate
d: Use mysql_options() instead. [-Wdeprecated-declarations]
  183 |       mysql_ssl_set(conn, key.empty() ? nullptr : key.c_str(),
      |       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  184 |                     cert.empty() ? nullptr : cert.c_str(), ca.empty() ? nullptr : ca.c_str(),
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  185 |                     capath.empty() ? nullptr : capath.c_str(),
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  186 |                     ciphers.empty() ? nullptr : ciphers.c_str());
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/mysql/mysql.h:465:1: note: declared here
  465 | mysql_ssl_set(MYSQL *mysql, const char *key, const char *cert, const char *ca,
      | ^~~~~~~~~~~~~
gmake[2]: *** [build/dbwrappers/CMakeFiles/dbwrappers.dir/build.make:146: build/dbwrappers/CMakeFiles/dbwrappers.dir/mysqldataset.cpp.o] Error 1
gmake[2]: Leaving directory '/home/redacted/kodi-build'
gmake[1]: *** [CMakeFiles/Makefile2:9802: build/dbwrappers/CMakeFiles/dbwrappers.dir/all] Error 2
gmake[1]: Leaving directory '/home/redacted/kodi-build'
gmake: *** [Makefile:146: all] Error 2
```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Ubuntu 24.04.2 LTS
 - Kodi version:
git nightly

**Comment by drelephant** [comment]
I used the template, previously I removed some headings but apparently the bot was not happy so I re-added them back.

**Comment by JackCarterSmith** [comment]
Not pretty sure but I think your libmysqlclient-dev package cause conflict with the build process.
Try removing it if you don't use it to see if it's compile.

If it works, then there is a problem with the include resolution path priorities.

**Comment by drelephant** [comment]
Thanks for the reply but unfortunately that didn't work.

`sudo apt remove libmysqlclient-dev`
`cmake --build . -- VERBOSE=1 -j$(getconf _NPROCESSORS_ONLN)`
```
<snip>
[100%] Built target legacy_interface
/home/redacted/kodi/xbmc/dbwrappers/mysqldataset.cpp:27:10: fatal error: mysql/errmsg.h: No such file or directory
   27 | #include <mysql/errmsg.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [build/dbwrappers/CMakeFiles/dbwrappers.dir/build.make:146: build/dbwrappers/CMakeFiles/dbwrappers.dir/mysqldataset.cpp.o] Error 1
gmake[2]: Leaving directory '/home/redacted/kodi-build'
gmake[1]: *** [CMakeFiles/Makefile2:9802: build/dbwrappers/CMakeFiles/dbwrappers.dir/all] Error 2
gmake[1]: Leaving directory '/home/redacted/kodi-build'
gmake: *** [Makefile:146: all] Error 2

```
Has nobody else on Ubuntu 24.04 LTS got this working?

**Comment by JackCarterSmith** [comment]
Do you have made a clean build dir after the apt remove? (using --fresh with cmake or simply deleting the build folder, mkdir it again and redo `cmake ../kodi -DENABLE_INTERNAL_FFMPEG=ON -DCMAKE_INSTALL_PREFIX=/usr/local -DCORE_PLATFORM_NAME=x11 -DAPP_RENDER_SYSTEM=gl`)
CMake keep lib and include path in cache.

I've build the latest Omega branch on debian again yesterday, without this kind of issue. Maybe it's related to the master branch indeed too.

**Comment by maitikeisi** [comment]
Had the same issue when I was trying to do a new master build on Ubuntu 24.04 LTS. Undoing the changes made in commit https://github.com/xbmc/xbmc/commit/d32a35c9cfbcbcf4f83f2108a9ae8a9b3df96f02 (reverting changes on file mysqldataset.h was enough to make it work) fixed the issue, and kodi was built successfully.
Something with that causes issue with building kodi on Ubuntu 24.04 LTS. Don't have enough knowledge to know what causes it to happen tho.

**Comment by garbear** [comment]
@fetzerch sorry for the noise but do you see an instant cmake fix?

**Comment by drelephant** [comment]
> Do you have made a clean build dir after the apt remove? (using --fresh with cmake or simply deleting the build folder, mkdir it again and redo `cmake ../kodi -DENABLE_INTERNAL_FFMPEG=ON -DCMAKE_INSTALL_PREFIX=/usr/local -DCORE_PLATFORM_NAME=x11 -DAPP_RENDER_SYSTEM=gl`) CMake keep lib and include path in cache.
> 
> I've build the latest Omega branch on debian again yesterday, without this kind of issue. Maybe it's related to the master branch indeed too.

That was it, after doing `rm -rf ~/kodi-build/*`, I was able to build!

Thanks so much!

Unfortunately it was after installing that I realized that I actually need to build Omega so some skins/plugins work, and then I had some more problems...

So I just opened a new Issue #26917 ...

I'll leave this open for if anyone can answer @garbear question.

**Comment by garbear** [comment]
I reported this build failure over at https://github.com/xbmc/xbmc/pull/26874. Reverting https://github.com/xbmc/xbmc/commit/d32a35c9cfbcbcf4f83f2108a9ae8a9b3df96f02 fixed the build for me on Ubuntu 24.04 ARM.

**Comment by damienruscoe** [comment]
This is the patch I have been using to fix the build

```
diff --git a/xbmc/dbwrappers/mysqldataset.cpp b/xbmc/dbwrappers/mysqldataset.cpp
index 7013f04db8..9eaca0e641 100644
--- a/xbmc/dbwrappers/mysqldataset.cpp
+++ b/xbmc/dbwrappers/mysqldataset.cpp
@@ -25,10 +25,8 @@
 
 #ifdef HAS_MYSQL
 #include <mysql/errmsg.h>
-#include <mysql/mysql.h>
 #elif defined(HAS_MARIADB)
 #include <mariadb/errmsg.h>
-#include <mariadb/mysql.h>
 #endif
 
 #ifdef TARGET_POSIX
diff --git a/xbmc/dbwrappers/mysqldataset.h b/xbmc/dbwrappers/mysqldataset.h
index 1f262c6fb6..036c436beb 100644
--- a/xbmc/dbwrappers/mysqldataset.h
+++ b/xbmc/dbwrappers/mysqldataset.h
@@ -12,8 +12,11 @@
 
 #include <string>
 
-struct st_mysql;
-using MYSQL = st_mysql;
+#ifdef HAS_MYSQL
+#include <mysql/mysql.h>
+#elif defined(HAS_MARIADB)
+#include <mariadb/mysql.h>
+#endif
 
 namespace dbiplus
 {
```

**Comment by ksooo** [comment]
> This is the patch I have been using to fix the build

Isn't this exactly the revert of https://github.com/xbmc/xbmc/commit/d32a35c9cfbcbcf4f83f2108a9ae8a9b3df96f02 ?

**Comment by damienruscoe** [comment]
> > This is the patch I have been using to fix the build
> 
> Isn't this exactly the revert of [d32a35c](https://github.com/xbmc/xbmc/commit/d32a35c9cfbcbcf4f83f2108a9ae8a9b3df96f02) ?

Yes! Yes it is. 
My bad. I saw it as part of a larger commit when I investigated the issue. I thought posting the minimum revert was being helpful
