### PR TITLE
[Bluray] Further linux bluray complie fix (Fix #26953).

### LINKED ISSUE #26953: Compile fails on Linux without libbluray when using -DENABLE_BLURAY=OFF. Bisected to recent commit.
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi git master fails to compile without libbluray installed even when using -DENABLE_BLURAY=OFF. After bisecting, the offending commit was by 78andyp on July 2, 2025: 6451b7937d811203597f902add034710a74958ab
"Fix retrieval of basepath."

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Successfully compiling without libbluray.

## Actual Behavior

Fails to compile without libbluray.

## Possible Fix

Wrap the `#include filesystem/BlurayDirectory.h` in URIUtils.cpp with an `#ifdef HAVE_LIBBLURAY`.

### To Reproduce

1. If installed, temporarily uninstall libbluray-dev
2. Clone master 
3. Configure with -DENABLE_BLURAY=OFF and try compiling

### Debuglog

The debuglog can be found here:
There is no debug log because compile fails with:

In file included from /test/kodi-r68700.git+28fb9320ad-bisect/xbmc/utils/URIUtils.cpp:16:
/test/kodi-r68700.git+28fb9320ad-bisect/xbmc/filesystem/BlurayDirectory.h:18:10: fatal error: libbluray/bluray.h: No such file or directory
   18 | #include <libbluray/bluray.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian Linux (sid)
 - Kodi version: Current git master (kodi-r68700.git+28fb9320ad)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by 78andyp**
## Description

Add missing `#ifdef HAVE_LIBBLURAY`.

## Motivation and context

Fix #26953.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by 78andyp** [comment]
Confirmed working in bug report.
