### ISSUE TITLE
[Bug] Kodi depends build failure: gettext symbol collision on Ubuntu 24.04

### ISSUE THREAD

**Issue by alpgul** [xbmc/xbmc#27830]
**System Information:**
- **OS:** Ubuntu 24.04 LTS
- **Affected Component:** `tools/depends/native/gettext`

**Description:**
When building Kodi dependencies (`depends`) on Ubuntu 24.04, the compilation fails during the `gettext` build stage due to a symbol collision (multiple definition error). This issue is likely caused by the stricter default linker/compiler settings introduced in newer toolchains provided with Ubuntu 24.04.

**Error Summary:**
During the `native/gettext` build process, the linker identifies multiple definitions of the same symbols and terminates the build.

**Workaround:**
To bypass this error and complete the build on Ubuntu 24.04, the `--allow-multiple-definition` flag must be passed to the linker via `LDFLAGS`. You can manually build the problematic module using the following command:

```bash
make -C tools/depends/native/gettext LDFLAGS="-Wl,--allow-multiple-definition"
```

**Expected Behavior:**
The Kodi `depends` system should be compatible with Ubuntu 24.04 default compiler settings out of the box, or the necessary flags should be automatically handled within the build scripts.

**Comment by alpgul** [comment]
It was due to ccache usage; it was fixed after disabling it.
