### PR TITLE
[ios/tvos] fallout from #20216 - MPMediaItem artwork

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Fix a build failure for ios/tvos introduced after @ksooo's work with #20216  

```
05:13:50 /Users/Shared/jenkins/workspace/IOS-ARM64/xbmc/platform/darwin/ios-common/AnnounceReceiver.mm:182:34: error: no member named 'Icon' in 'PVR::CPVREpgInfoTag'
05:13:50         auto epg_icon = epg_now->Icon();
05:13:50                         ~~~~~~~  ^
05:13:50 1 error generated.
05:13:50
```

## Motivation and context
Fixes build failure on ios

## How has this been tested?
To be - Hoping @sy6sy2 might have a quick setup to test its working as intended and getting the correct icon.

## What is the effect on users?
N/A

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ksooo** [comment]
IIRC, TVOS build also suffers from this.

**Comment by sy6sy2** [comment]
Hi! Sorry for being absent seen some times (real life...). 
I will try it on iOS, what specific part should I check?

**Comment by fuzzard** [comment]
Greatly appreciated, its the MPMedia player art that is effected. ie run a pvr item and look at the ios NowPlaying controls and hopefully the epg icon should appear.

**Review by ksooo — APPROVED** [review]

**Comment by sy6sy2** [comment]
If my test procedure is correct, it seems to works well. (Tested build: https://jenkins.kodi.tv/job/IOS-ARM64/16502/)
IMG_0104

**Review by sy6sy2 — APPROVED** [review]

**Comment by fuzzard** [comment]
Yeah, that's great. Thanks @sy6sy2
