### PR TITLE
Scoped enum VideoContentType is not formattable

### PR DESCRIPTION
**Pull request by janbar**
Cast to int the scoped enum VideoContentType to be formattable, and fix the build with g++ 13.3.0 on Ubuntu 24.04 x86-64.

/usr/include/fmt/core.h:1757:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization

## Description
Fix compile error with g++ 13.3.0 on Ubuntu 24.04 x86_64

## Motivation and context
Build of Kodi cannot be achieved with g++ 13.3.0 (Ubuntu 24.04)

## How has this been tested?
No change

## What is the effect on users?
No change

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
This was brought up internally I believe. The consensus was that a formatter should be made, as a number returned in the logging is effectively useless in terms of relevant information.

Something like https://github.com/xbmc/xbmc/blob/161bedb04dc0ae7db07f308deda709d483a923dd/xbmc/cores/VideoSettings.h#L44-L54 was my understanding

**Comment by janbar** [comment]
@fuzzard , do you want I change the fix in this way ?
That means I add the template and the static map in `VideoDatabase.h`.

**Comment by fuzzard** [comment]
Best to try ping @notspiff @lrusak or maybe @neo1973 for some advice probably

**Comment by neo1973** [comment]
@janbar: I suggest doing it like this:
```cpp
template<>
struct fmt::formatter<VideoDbContentType> : fmt::formatter<std::string_view>
{
  template<typename FormatContext>
  constexpr auto format(const VideoDbContentType& type, FormatContext& ctx)
  {
    return fmt::formatter<string_view>::format(enumToSV(type), ctx);
  }

private:
  static constexpr std::string_view enumToSV(VideoDbContentType type)
  {
    using namespace std::literals::string_view_literals;
    switch (type)
    {
      case VideoDbContentType::UNKNOWN:
        return "unknown"sv;
      case VideoDbContentType::MOVIES:
        return "movies"sv;
      case VideoDbContentType::TVSHOWS:
        return "TV shows"sv;
      case VideoDbContentType::MUSICVIDEOS:
        return "music videos"sv;
      case VideoDbContentType::EPISODES:
        return "episodes"sv;
      case VideoDbContentType::MOVIE_SETS:
        return "movie sets"sv;
      case VideoDbContentType::MUSICALBUMS:
        return "music albums"sv;
    };
    throw std::invalid_argument("no videodb content string found");
  }
};
```
Doing the switch-case has the nice benefit that most compilers will produce a warning if the enum is extended but the formatter isn't.

> Also there is a member to translate type to string. So I could use this member instead add a static map.

I wouldn't use that function. It doesn't cover all enum values and it's main purpose is to convert `VideoDbContentType` to a string that can be used in SQL queries.

File: xbmc/video/VideoDatabase.h [hunk 1]
```diff
@@ -180,6 +181,40 @@ enum class VideoDbContentType
   MUSICALBUMS = 6
 };
 
+template<>
+struct fmt::formatter<VideoDbContentType> : fmt::formatter<std::string_view>
```
Comment (ksooo) [inline xbmc/video/VideoDatabase.h:185]: For `std::string_view`, `#include <string_view>` should be added.

**Comment by janbar** [comment]
Jenkins stopperd to complain about thé style. So it is ready to be merged.

**Review by neo1973 — APPROVED** [review]

File: xbmc/video/VideoDatabase.h [hunk 2]
```diff
@@ -180,6 +184,40 @@ enum class VideoDbContentType
...
+      case VideoDbContentType::MUSICVIDEOS:
+        return "music videos"sv;
+      case VideoDbContentType::EPISODES:
+        return "episodes"sv;
+      case VideoDbContentType::MOVIE_SETS:
+        return "movie sets"sv;
+      case VideoDbContentType::MUSICALBUMS:
+        return "music albums"sv;
+    };
+    throw std::invalid_argument("no videodb content string found");
```
Comment (CrystalP) [inline xbmc/video/VideoDatabase.h:217]: could be just me, isn't throwing excessive?
As far as I know Kodi only has a catch at the top level of threads except for few specific areas of the code (db).
```
default:
  return {};
```
 would be fine?

Comment (neo1973) [reply xbmc/video/VideoDatabase.h:217]: I think an exception is OK here. Adding a `default` has the downside that the compiler stops issuing warnings if not all enum cases are handled. Also, if we should ever get something that's not a `VideoDbContentType` something went really wrong and an exception is adequate.

**Comment by lrusak** [comment]
@neo1973 is there a reason you want to use a switch/case instead of our CMap?

Is it because of the custom enum values?

**Comment by neo1973** [comment]
> Is it because of the custom enum values?

I would like to have some kind of compiler hint if the enum is extended and the formatter isn't. Adding a `CONTENT_TYPE_MAX` and checking that with a `static_assert` would work as well but I don't really see a benefit over the switch-case for this use case.

**Comment by lrusak** [comment]
> > Is it because of the custom enum values?
> 
> 
> 
> I would like to have some kind of compiler hint if the enum is extended and the formatter isn't. Adding a `CONTENT_TYPE_MAX` and checking that with a `static_assert` would work as well but I don't really see a benefit over the switch-case for this use case.

I'm ok with that. The only reason I ask is because we use CMap with the static_assert in other places already and it would be nice to be consistent (if the use case fits).

**Review by howie-f — APPROVED** [review]
works nice, thank you guys
