### PR TITLE
Update flatbuffers to v23.1.21

### PR DESCRIPTION
**Pull request by cscd98**
## Description
This updates the flatbuffers version referenced in tools/depends from v2.0.0 to v23.1.21. The substantial version change is due to them switching to yearly release versions :(

## Motivation and context
PR is purely to update flatbuffers to the latest version

## How has this been tested?
Before this can be tested https://github.com/google/flatbuffers/archive/refs/tags/v23.1.21.tar.gz must be uploaded to http://mirrors.kodi.tv/build-deps/sources/ and renamed to flatbuffers-23.1.21.tar.gz

## What is the effect on users?
None facing

## Types of change
- [x] **Improvement** (non-breaking change which improves existing functionality)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
Your description in the `Motivation and context` section of your OP is wrong. We already determined that the bump isn't required to build Kodi properly but rather it was user error.

Please update the description to reflect that this PR is purely to update flatbuffers to the latest version and that it's not because of an issue.

**Comment by craigcarnell** [comment]
@lrusak Is this OK?

**Comment by garbear** [comment]
I did a round of test builds with flatbuffers 23.1.4 (will post links later). However, macos fails to build:

```
13:43:33 [  2%] Building CXX object CMakeFiles/flatc.dir/src/binary_annotator.cpp.o
13:43:35 /Users/Shared/jenkins/workspace/OSX-64/build/build/flatc/src/flatc/src/binary_annotator.cpp:169:40: error: 'value' is unavailable: introduced in macOS 10.14
13:43:35   if (!IsValidOffset(root_table_offset.value())) {
13:43:35                                        ^
13:43:35 /Applications/Xcode12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/optional:944:33: note: 'value' has been explicitly marked unavailable here
13:43:35     constexpr value_type const& value() const&
13:43:35                                 ^
```

CI run: https://jenkins.kodi.tv/view/Automation/job/BuildMulti-Choice/997/

**Comment by craigcarnell** [comment]
@garbear 

"What version of the compiler are using? It seems likes it is not supporting everything in the C++17 standard. https://en.cppreference.com/w/cpp/utility/optional"

**Comment by craigcarnell** [comment]
@lrusak Can you answer that at all? I think the question is about what level of c++ standard the mac os compiler being used in ? jenkins adheres to

**Comment by craigcarnell** [comment]
@lrusak Hmm if it's because of an older platform, perhaps I could just use 2.0.0 if platform is darwin? And we can use the newer flatbuffers on more modern compilers? Does that sound like a sensible fix?

**Comment by lrusak** [comment]
> @lrusak Hmm if it's because of an older platform, perhaps I could just use 2.0.0 if platform is darwin? And we can use the newer flatbuffers on more modern compilers? Does that sound like a sensible fix?

As Kodi is a multiplatform project we should try and keep all platforms as equal as possible (within reason).

**Comment by garbear** [comment]
@craigcarnell If you rebase on master instead of merging master to your PR then jenkins will be able to build it

**Comment by craigcarnell** [comment]
@garbear 

```
git pull
git rebase master
git config pull.rebase true
git push origin update/flatbuffers-23.1.4 
Successfully rebased and updated refs/heads/update/flatbuffers-23.1.4.
```

Did that work? :)

**Comment by garbear** [comment]
Unfortunately no: https://github.com/xbmc/xbmc/pull/22515/commits

I use `git pull --rebase`

you're best off hard-resetting to upstream/master and cherry picking the commit, then force pushing. You know you're done it right when got push doesn't work and got push --force does

**Comment by craigcarnell** [comment]
@garbear Done. Hopefully..

**Comment by garbear** [comment]
Now you got it :slightly_smiling_face: https://github.com/xbmc/xbmc/commits/6df4115edb7a2cd78c7782f09e9a3d465a011a3b - your commit is applied on top, history here is clean

**Comment by craigcarnell** [comment]
@garbear @lrusak Is this a suitable workaround? You cannot build kodi at the moment with a modern environment like Ubuntu 22.10 with an older flatbuffers version.

**Comment by lrusak** [comment]
> @garbear @lrusak Is this a suitable workaround? You cannot build kodi at the moment with a modern environment like Ubuntu 22.10 with an older flatbuffers version. At least not without downloading flatc v2.0.0 binary.

No sorry. Just use the internal flatbuffers if you are having issues.

**Comment by craigcarnell** [comment]
Undo :)
