### PR TITLE
[cmake] fail if rapidjson is not found

### PR DESCRIPTION
**Pull request by wsnipex**
the packagename in find_package_handle_standard_args must be exactly the same as the one find_package has been called with.

fixes not erroring out in cmake when rapidjson is not found.

@Rechi sry, I requested the change, so I fix it ;)

### CODE REVIEW

**Review by Rechi — APPROVED** [review]

**Comment by MilhouseVH** [comment]
Native Linux builds now fail with this PR:
```
-- Found FriBidi: /usr/lib/x86_64-linux-gnu/libfribidi.so (found version "0.19.7")
-- Found PCRE: /usr/lib/x86_64-linux-gnu/libpcrecpp.so (found version "8.38")
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find RapidJSON (missing: RapidJSON_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindRapidJSON.cmake:22 (find_package_handle_standard_args)
  cmake/scripts/common/Macros.cmake:315 (find_package)
  CMakeLists.txt:169 (core_require_dep)


-- Configuring incomplete, errors occurred!
See also "/home/neil/projects/kodi.git/CMakeFiles/CMakeOutput.log".
See also "/home/neil/projects/kodi.git/CMakeFiles/CMakeError.log".
```
I do not have RapidJSON installed on the host.

Without this PR:
```
-- Could NOT find RAPIDJSON (missing:  RapidJSON_INCLUDE_DIR)
```
So for some reason it's not downloading from the mirror...

**Comment by MilhouseVH** [comment]
Sorry, it doesn't build successfully when RapidJSON is not found (obviously):
```
[ 85%] Built target guilib
/home/neil/projects/kodi.git/xbmc/utils/JSONVariantWriter.cpp:23:36: fatal error: rapidjson/prettywriter.h: No such file or directory
compilation terminated.
```
My question is, should #8008 now be downloading the source when it's not installed on the host?

I'm building on Ubuntu 16.04 and can `apt-get install rapidjson-dev` which is v0.12, but would rather build with v1.0.2 if possible.

**Comment by wsnipex** [comment]
it will not automatically download anything, we only do that for libdvd and ffmpeg(if needed).

you can find 1.0.2 in our build depends ppa

**Comment by MilhouseVH** [comment]
Ah ok, thanks for the clarification - it's not often I build native. :)

**Comment by wsnipex** [comment]
updated to check for min version 1.0.2
jenkins build this please

**Comment by wsnipex** [comment]
meh, windows is special again.
jenkins build this please
