### PR TITLE
[backport] [linux] fix drm object build with gcc-4.9

### PR DESCRIPTION
**Pull request by bkuhls**
Fixes build error introduced by PR #18858

kodi/xbmc/windowing/gbm/drm/DRMObject.cpp: In member function 'std::tuple<bool, long unsigned int> KODI::WINDOWING::GBM::CDRMObject::GetPropertyValue(const string&, const string&) const':
kodi/xbmc/windowing/gbm/drm/DRMObject.cpp:103:39: error: converting to 'std::tuple<bool, long unsigned int>' from initializer list would use explicit constructor 'constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = bool; _U2 = long long unsigned int&; <template-parameter-2-3> = void; _T1 = bool; _T2 = long unsigned int]'
     return {true, prop->enums[j].value};

Backport of https://github.com/xbmc/xbmc/pull/19020

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] All new and existing tests passed

### CODE REVIEW

**Review by lrusak — APPROVED** [review]
LGTM

**Review by garbear — APPROVED** [review]
