### PR TITLE
ZeroconfMDNS.cpp: add header to fix compile with gcc 4.9 & uClibc

### PR DESCRIPTION
**Pull request by bkuhls**
Without the patch compilation fails with
ZeroconfMDNS.cpp:133:139: error: ‘htons’ was not declared in this scope

Infos about the toolchain used:
gcc version 4.9.3 (Buildroot 2016.05-00002-g5dabb45), uClibc-NG 1.0.15

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
jenkins build this please
